"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .flsa_status_type import FlsaStatusType
from enum import Enum
from gusto_embedded_v_2025_11_15 import models
from gusto_embedded_v_2025_11_15.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CompensationsRequestBodyPaymentUnit(str, Enum):
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'."""

    HOUR = "Hour"
    WEEK = "Week"
    MONTH = "Month"
    YEAR = "Year"
    PAYCHECK = "Paycheck"


class CompensationsRequestBodyMinimumWagesTypedDict(TypedDict):
    uuid: NotRequired[str]
    r"""The UUID of the minimum wage."""


class CompensationsRequestBodyMinimumWages(BaseModel):
    uuid: Optional[str] = None
    r"""The UUID of the minimum wage."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CompensationsRequestBodyTypedDict(TypedDict):
    r"""Request body for creating a compensation."""

    rate: str
    r"""The dollar amount paid per payment unit."""
    payment_unit: CompensationsRequestBodyPaymentUnit
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'."""
    flsa_status: FlsaStatusType
    r"""The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ('Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company."""
    effective_date: NotRequired[str]
    r"""The effective date for this compensation."""
    title: NotRequired[str]
    r"""The job title for this compensation."""
    adjust_for_minimum_wage: NotRequired[bool]
    r"""Whether the compensation should be adjusted to minimum wage during payroll calculation."""
    minimum_wages: NotRequired[List[CompensationsRequestBodyMinimumWagesTypedDict]]


class CompensationsRequestBody(BaseModel):
    r"""Request body for creating a compensation."""

    rate: str
    r"""The dollar amount paid per payment unit."""

    payment_unit: CompensationsRequestBodyPaymentUnit
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be 'Paycheck'."""

    flsa_status: FlsaStatusType
    r"""The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ('Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company."""

    effective_date: Optional[str] = None
    r"""The effective date for this compensation."""

    title: Optional[str] = None
    r"""The job title for this compensation."""

    adjust_for_minimum_wage: Optional[bool] = None
    r"""Whether the compensation should be adjusted to minimum wage during payroll calculation."""

    minimum_wages: Optional[List[CompensationsRequestBodyMinimumWages]] = None

    @field_serializer("flsa_status")
    def serialize_flsa_status(self, value):
        if isinstance(value, str):
            try:
                return models.FlsaStatusType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["effective_date", "title", "adjust_for_minimum_wage", "minimum_wages"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
