"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from gusto_embedded_v_2025_11_15.types import BaseModel
from typing_extensions import TypedDict


class ExternalPayrollCreateRequestTypedDict(TypedDict):
    r"""The request body for creating an external payroll."""

    check_date: date
    r"""The check date of the external payroll."""
    payment_period_start_date: date
    r"""The start date of the external payroll payment period."""
    payment_period_end_date: date
    r"""The end date of the external payroll payment period."""


class ExternalPayrollCreateRequest(BaseModel):
    r"""The request body for creating an external payroll."""

    check_date: date
    r"""The check date of the external payroll."""

    payment_period_start_date: date
    r"""The start date of the external payroll payment period."""

    payment_period_end_date: date
    r"""The end date of the external payroll payment period."""
