"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2025_11_15.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PartnerManagedCompanyTypedDict(TypedDict):
    r"""Object returned when creating a partner managed company"""

    access_token: NotRequired[str]
    r"""Access token that can be used for OAuth access to the account. Access tokens expire 2 hours after they are issued."""
    refresh_token: NotRequired[str]
    r"""Refresh token that can be exchanged for a new access token."""
    company_uuid: NotRequired[str]
    r"""Gusto's UUID for the company"""
    expires_in: NotRequired[int]
    r"""Time of access_token expiration in seconds"""


class PartnerManagedCompany(BaseModel):
    r"""Object returned when creating a partner managed company"""

    access_token: Optional[str] = None
    r"""Access token that can be used for OAuth access to the account. Access tokens expire 2 hours after they are issued."""

    refresh_token: Optional[str] = None
    r"""Refresh token that can be exchanged for a new access token."""

    company_uuid: Optional[str] = None
    r"""Gusto's UUID for the company"""

    expires_in: Optional[int] = None
    r"""Time of access_token expiration in seconds"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["access_token", "refresh_token", "company_uuid", "expires_in"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
