"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded_v_2025_11_15.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MigrationStatus(str, Enum):
    r"""The migration status. Always returns `success` for a successful migration."""

    SUCCESS = "success"


class PartnerManagedCompanyMigrateResponseTypedDict(TypedDict):
    company_uuid: NotRequired[str]
    r"""The company UUID"""
    migration_status: NotRequired[MigrationStatus]
    r"""The migration status. Always returns `success` for a successful migration."""


class PartnerManagedCompanyMigrateResponse(BaseModel):
    company_uuid: Optional[str] = None
    r"""The company UUID"""

    migration_status: Optional[MigrationStatus] = None
    r"""The migration status. Always returns `success` for a successful migration."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["company_uuid", "migration_status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
