"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2025_11_15.types import BaseModel
from gusto_embedded_v_2025_11_15.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadataTypedDict(
    TypedDict
):
    information_request_uuid: str
    r"""UUID of the information request"""


class PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata(BaseModel):
    information_request_uuid: str
    r"""UUID of the information request"""


class PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiTypedDict(TypedDict):
    r"""Unblock option to resolve a credit blocker by responding to high risk fraud RFI"""

    check_date: str
    r"""The payment check date associated with the unblock option"""
    metadata: (
        PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadataTypedDict
    )
    unblock_type: Literal["respond_to_high_risk_fraud_rfi"]
    r"""The type of unblock option for the credit blocker"""


class PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfi(BaseModel):
    r"""Unblock option to resolve a credit blocker by responding to high risk fraud RFI"""

    check_date: str
    r"""The payment check date associated with the unblock option"""

    metadata: PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata

    unblock_type: Annotated[
        Annotated[
            Literal["respond_to_high_risk_fraud_rfi"],
            AfterValidator(validate_const("respond_to_high_risk_fraud_rfi")),
        ],
        pydantic.Field(alias="unblock_type"),
    ] = "respond_to_high_risk_fraud_rfi"
    r"""The type of unblock option for the credit blocker"""


try:
    PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfi.model_rebuild()
except NameError:
    pass
