"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded_v_2025_11_15 import models, utils
from gusto_embedded_v_2025_11_15.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TotalsTypedDict(TypedDict):
    r"""The subtotals for the payroll."""

    company_debit: NotRequired[str]
    r"""The total company debit for the payroll."""
    net_pay_debit: NotRequired[str]
    r"""The total company net pay for the payroll."""
    child_support_debit: NotRequired[str]
    r"""The total child support debit for the payroll."""
    reimbursement_debit: NotRequired[str]
    r"""The total reimbursements for the payroll."""
    tax_debit: NotRequired[str]
    r"""The total tax debit for the payroll."""


class Totals(BaseModel):
    r"""The subtotals for the payroll."""

    company_debit: Optional[str] = None
    r"""The total company debit for the payroll."""

    net_pay_debit: Optional[str] = None
    r"""The total company net pay for the payroll."""

    child_support_debit: Optional[str] = None
    r"""The total child support debit for the payroll."""

    reimbursement_debit: Optional[str] = None
    r"""The total reimbursements for the payroll."""

    tax_debit: Optional[str] = None
    r"""The total tax debit for the payroll."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "company_debit",
                "net_pay_debit",
                "child_support_debit",
                "reimbursement_debit",
                "tax_debit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TaxesTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The amount paid for this tax."""
    amount: NotRequired[str]
    r"""The total amount paid by both employer and employee for this tax."""


class Taxes(BaseModel):
    name: Optional[str] = None
    r"""The amount paid for this tax."""

    amount: Optional[str] = None
    r"""The total amount paid by both employer and employee for this tax."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayrollReceiptPaymentMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The employee's compensation payment method."""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"


class PayrollReceiptEmployeeCompensationsTypedDict(TypedDict):
    employee_uuid: NotRequired[str]
    r"""The UUID of the employee."""
    employee_first_name: NotRequired[str]
    r"""The first name of the employee."""
    employee_last_name: NotRequired[str]
    r"""The last name of the employee."""
    payment_method: NotRequired[PayrollReceiptPaymentMethod]
    r"""The employee's compensation payment method."""
    net_pay: NotRequired[str]
    r"""The employee's net pay. Net pay paid by check is available for reference but is not included in the `[\"totals\"][\"net_pay_debit\"]` amount."""
    total_tax: NotRequired[str]
    r"""The total of employer and employee taxes for the pay period."""
    total_garnishments: NotRequired[str]
    r"""The total garnishments for the pay period."""
    child_support_garnishment: NotRequired[str]
    r"""The total child support garnishment for the pay period."""
    total_reimbursement: NotRequired[str]
    r"""The total reimbursement for the pay period."""


class PayrollReceiptEmployeeCompensations(BaseModel):
    employee_uuid: Optional[str] = None
    r"""The UUID of the employee."""

    employee_first_name: Optional[str] = None
    r"""The first name of the employee."""

    employee_last_name: Optional[str] = None
    r"""The last name of the employee."""

    payment_method: Optional[PayrollReceiptPaymentMethod] = None
    r"""The employee's compensation payment method."""

    net_pay: Optional[str] = None
    r"""The employee's net pay. Net pay paid by check is available for reference but is not included in the `[\"totals\"][\"net_pay_debit\"]` amount."""

    total_tax: Optional[str] = None
    r"""The total of employer and employee taxes for the pay period."""

    total_garnishments: Optional[str] = None
    r"""The total garnishments for the pay period."""

    child_support_garnishment: Optional[str] = None
    r"""The total child support garnishment for the pay period."""

    total_reimbursement: Optional[str] = None
    r"""The total reimbursement for the pay period."""

    @field_serializer("payment_method")
    def serialize_payment_method(self, value):
        if isinstance(value, str):
            try:
                return models.PayrollReceiptPaymentMethod(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "employee_uuid",
                "employee_first_name",
                "employee_last_name",
                "payment_method",
                "net_pay",
                "total_tax",
                "total_garnishments",
                "child_support_garnishment",
                "total_reimbursement",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LicenseeTypedDict(TypedDict):
    r"""The licensed payroll processor"""

    name: NotRequired[str]
    r"""Always the fixed string \"Gusto, Zenpayroll Inc.\" """
    address: NotRequired[str]
    r"""Always the fixed string \"525 20th St\" """
    city: NotRequired[str]
    r"""Always the fixed string \"San Francisco\" """
    state: NotRequired[str]
    r"""Always the fixed string \"CA\" """
    postal_code: NotRequired[str]
    r"""Always the fixed string \"94107\" """
    phone_number: NotRequired[str]
    r"""Always the fixed string \"4157778888\" """


class Licensee(BaseModel):
    r"""The licensed payroll processor"""

    name: Optional[str] = None
    r"""Always the fixed string \"Gusto, Zenpayroll Inc.\" """

    address: Optional[str] = None
    r"""Always the fixed string \"525 20th St\" """

    city: Optional[str] = None
    r"""Always the fixed string \"San Francisco\" """

    state: Optional[str] = None
    r"""Always the fixed string \"CA\" """

    postal_code: Optional[str] = None
    r"""Always the fixed string \"94107\" """

    phone_number: Optional[str] = None
    r"""Always the fixed string \"4157778888\" """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "address", "city", "state", "postal_code", "phone_number"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayrollReceiptTypedDict(TypedDict):
    payroll_uuid: NotRequired[str]
    r"""A unique identifier of the payroll receipt."""
    company_uuid: NotRequired[str]
    r"""A unique identifier of the company for the payroll."""
    name_of_sender: NotRequired[str]
    r"""The name of the company by whom the payroll was paid"""
    name_of_recipient: NotRequired[str]
    r"""Always the fixed string \"Payroll Recipients\" """
    recipient_notice: NotRequired[str]
    r"""Always the fixed string \"Payroll recipients include the employees listed below plus the tax agencies for the taxes listed below.\" """
    debit_date: NotRequired[str]
    r"""The debit or funding date for the payroll"""
    license: NotRequired[str]
    r"""Always the fixed string \"ZenPayroll, Inc., dba Gusto is a licensed money transmitter. For more about Gusto’s licenses and your state-specific rights to request information, submit complaints, dispute errors, or cancel transactions, visit our license page.\" """
    license_uri: NotRequired[str]
    r"""URL for the license information for the licensed payroll processor. Always the fixed string \"https://gusto.com/about/licenses\" """
    right_to_refund: NotRequired[str]
    liability_of_licensee: NotRequired[str]
    totals: NotRequired[TotalsTypedDict]
    r"""The subtotals for the payroll."""
    taxes: NotRequired[List[TaxesTypedDict]]
    r"""An array of totaled employer and employee taxes for the pay period."""
    employee_compensations: NotRequired[
        List[PayrollReceiptEmployeeCompensationsTypedDict]
    ]
    r"""An array of employee compensations and withholdings for this payroll"""
    licensee: NotRequired[LicenseeTypedDict]
    r"""The licensed payroll processor"""


class PayrollReceipt(BaseModel):
    payroll_uuid: Optional[str] = None
    r"""A unique identifier of the payroll receipt."""

    company_uuid: Optional[str] = None
    r"""A unique identifier of the company for the payroll."""

    name_of_sender: Optional[str] = None
    r"""The name of the company by whom the payroll was paid"""

    name_of_recipient: Optional[str] = None
    r"""Always the fixed string \"Payroll Recipients\" """

    recipient_notice: Optional[str] = None
    r"""Always the fixed string \"Payroll recipients include the employees listed below plus the tax agencies for the taxes listed below.\" """

    debit_date: Optional[str] = None
    r"""The debit or funding date for the payroll"""

    license: Optional[str] = None
    r"""Always the fixed string \"ZenPayroll, Inc., dba Gusto is a licensed money transmitter. For more about Gusto’s licenses and your state-specific rights to request information, submit complaints, dispute errors, or cancel transactions, visit our license page.\" """

    license_uri: Optional[str] = None
    r"""URL for the license information for the licensed payroll processor. Always the fixed string \"https://gusto.com/about/licenses\" """

    right_to_refund: Optional[str] = None

    liability_of_licensee: Optional[str] = None

    totals: Optional[Totals] = None
    r"""The subtotals for the payroll."""

    taxes: Optional[List[Taxes]] = None
    r"""An array of totaled employer and employee taxes for the pay period."""

    employee_compensations: Optional[List[PayrollReceiptEmployeeCompensations]] = None
    r"""An array of employee compensations and withholdings for this payroll"""

    licensee: Optional[Licensee] = None
    r"""The licensed payroll processor"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "payroll_uuid",
                "company_uuid",
                "name_of_sender",
                "name_of_recipient",
                "recipient_notice",
                "debit_date",
                "license",
                "license_uri",
                "right_to_refund",
                "liability_of_licensee",
                "totals",
                "taxes",
                "employee_compensations",
                "licensee",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
