"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded_v_2025_11_15.types import BaseModel, UNSET_SENTINEL
from gusto_embedded_v_2025_11_15.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewHeaderXGustoAPIVersion(str, Enum):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15 = "2025-11-15"


class PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequestBodyTypedDict(TypedDict):
    employee_uuid: str
    r"""The UUID of the employee"""
    policy_uuid: str
    r"""The UUID of the time off policy"""
    start_date: str
    r"""The start date of the time off request (YYYY-MM-DD)"""
    end_date: str
    r"""The end date of the time off request (YYYY-MM-DD)"""
    days: Dict[str, str]
    r"""An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g. {\"2025-01-20\": \"8.000\"})"""
    request_uuid: NotRequired[str]
    r"""The UUID of an existing time off request to preview changes for"""


class PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequestBody(BaseModel):
    employee_uuid: str
    r"""The UUID of the employee"""

    policy_uuid: str
    r"""The UUID of the time off policy"""

    start_date: str
    r"""The start date of the time off request (YYYY-MM-DD)"""

    end_date: str
    r"""The end date of the time off request (YYYY-MM-DD)"""

    days: Dict[str, str]
    r"""An object where keys are dates in YYYY-MM-DD format and values are hours as string decimals (e.g. {\"2025-01-20\": \"8.000\"})"""

    request_uuid: Optional[str] = None
    r"""The UUID of an existing time off request to preview changes for"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["request_uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequestTypedDict(TypedDict):
    company_uuid: str
    r"""The UUID of the company"""
    body: PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequestBodyTypedDict
    x_gusto_api_version: NotRequired[
        PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequest(BaseModel):
    company_uuid: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    body: Annotated[
        PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[
            PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewHeaderXGustoAPIVersion
        ],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PostV1CompaniesCompanyUUIDTimeOffRequestsPreviewHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
