"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from enum import Enum
from gusto_embedded_v_2025_11_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from gusto_embedded_v_2025_11_15.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostV1CompaniesCompanyIDPeopleBatchesHeaderXGustoAPIVersion(str, Enum):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15 = "2025-11-15"


class BatchAction(str, Enum):
    r"""The action to perform on the batch"""

    CREATE = "create"


class PostV1CompaniesCompanyIDPeopleBatchesEntityType(str, Enum):
    r"""The type of entity to create"""

    EMPLOYEE = "employee"


class PersonTypedDict(TypedDict):
    external_id: str
    r"""External identifier for the person"""
    first_name: str
    r"""Legal first name"""
    last_name: str
    r"""Legal last name"""
    middle_initial: NotRequired[Nullable[str]]
    r"""Middle initial"""
    preferred_first_name: NotRequired[Nullable[str]]
    r"""Preferred first name"""
    email: NotRequired[Nullable[str]]
    r"""Personal email address"""
    work_email: NotRequired[Nullable[str]]
    r"""Work email address"""
    ssn: NotRequired[Nullable[str]]
    r"""Social Security Number (format: xxx-xx-xxxx)"""
    date_of_birth: NotRequired[Nullable[date]]
    r"""Date of birth (YYYY-MM-DD)"""
    self_onboarding: NotRequired[Nullable[bool]]
    r"""Whether the employee will complete their own onboarding"""


class Person(BaseModel):
    external_id: str
    r"""External identifier for the person"""

    first_name: str
    r"""Legal first name"""

    last_name: str
    r"""Legal last name"""

    middle_initial: OptionalNullable[str] = UNSET
    r"""Middle initial"""

    preferred_first_name: OptionalNullable[str] = UNSET
    r"""Preferred first name"""

    email: OptionalNullable[str] = UNSET
    r"""Personal email address"""

    work_email: OptionalNullable[str] = UNSET
    r"""Work email address"""

    ssn: OptionalNullable[str] = UNSET
    r"""Social Security Number (format: xxx-xx-xxxx)"""

    date_of_birth: OptionalNullable[date] = UNSET
    r"""Date of birth (YYYY-MM-DD)"""

    self_onboarding: OptionalNullable[bool] = UNSET
    r"""Whether the employee will complete their own onboarding"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "middle_initial",
                "preferred_first_name",
                "email",
                "work_email",
                "ssn",
                "date_of_birth",
                "self_onboarding",
            ]
        )
        nullable_fields = set(
            [
                "middle_initial",
                "preferred_first_name",
                "email",
                "work_email",
                "ssn",
                "date_of_birth",
                "self_onboarding",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PostV1CompaniesCompanyIDPeopleBatchesHomeAddressTypedDict(TypedDict):
    r"""Home address for the employee"""

    street_1: str
    r"""Street address line 1"""
    city: str
    r"""City"""
    state: str
    r"""State abbreviation"""
    zip_code: str
    r"""ZIP code"""
    street_2: NotRequired[str]
    r"""Street address line 2"""
    country: NotRequired[str]
    r"""Country (defaults to USA)"""
    work_from_home: NotRequired[bool]
    r"""If true, a company work address will be created based on this home address and the `work_address` property is not allowed."""


class PostV1CompaniesCompanyIDPeopleBatchesHomeAddress(BaseModel):
    r"""Home address for the employee"""

    street_1: str
    r"""Street address line 1"""

    city: str
    r"""City"""

    state: str
    r"""State abbreviation"""

    zip_code: Annotated[str, pydantic.Field(alias="zip")]
    r"""ZIP code"""

    street_2: Optional[str] = None
    r"""Street address line 2"""

    country: Optional[str] = None
    r"""Country (defaults to USA)"""

    work_from_home: Optional[bool] = None
    r"""If true, a company work address will be created based on this home address and the `work_address` property is not allowed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["street_2", "country", "work_from_home"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostV1CompaniesCompanyIDPeopleBatchesWorkAddressTypedDict(TypedDict):
    r"""Specify the company work location for the employee"""

    location_uuid: str
    r"""UUID of an existing company work location"""


class PostV1CompaniesCompanyIDPeopleBatchesWorkAddress(BaseModel):
    r"""Specify the company work location for the employee"""

    location_uuid: str
    r"""UUID of an existing company work location"""


class PostV1CompaniesCompanyIDPeopleBatchesJobTypedDict(TypedDict):
    r"""Job details for the employee (required if compensation is provided)"""

    title: str
    r"""Job title"""
    hire_date: date
    r"""The date when the employee was hired or rehired for the job."""
    two_percent_shareholder: NotRequired[bool]
    r"""Whether the employee owns at least 2% of the company. Can only be `true` for S-Corp companies."""
    state_wc_covered: NotRequired[Nullable[bool]]
    r"""Whether this job is eligible for workers' compensation coverage in the state of Washington (WA)."""
    state_wc_class_code: NotRequired[Nullable[str]]
    r"""The risk class code for workers' compensation in Washington state. Please visit [Washington state's Risk Class page](https://www.lni.wa.gov/insurance/rates-risk-classes/risk-classes-for-workers-compensation/risk-class-lookup#/) to learn more."""


class PostV1CompaniesCompanyIDPeopleBatchesJob(BaseModel):
    r"""Job details for the employee (required if compensation is provided)"""

    title: str
    r"""Job title"""

    hire_date: date
    r"""The date when the employee was hired or rehired for the job."""

    two_percent_shareholder: Optional[bool] = None
    r"""Whether the employee owns at least 2% of the company. Can only be `true` for S-Corp companies."""

    state_wc_covered: OptionalNullable[bool] = UNSET
    r"""Whether this job is eligible for workers' compensation coverage in the state of Washington (WA)."""

    state_wc_class_code: OptionalNullable[str] = UNSET
    r"""The risk class code for workers' compensation in Washington state. Please visit [Washington state's Risk Class page](https://www.lni.wa.gov/insurance/rates-risk-classes/risk-classes-for-workers-compensation/risk-class-lookup#/) to learn more."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["two_percent_shareholder", "state_wc_covered", "state_wc_class_code"]
        )
        nullable_fields = set(["state_wc_covered", "state_wc_class_code"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PostV1CompaniesCompanyIDPeopleBatchesDepartmentTypedDict(TypedDict):
    r"""Department details for the employee"""

    department_uuid: str
    r"""UUID of an existing company department"""


class PostV1CompaniesCompanyIDPeopleBatchesDepartment(BaseModel):
    r"""Department details for the employee"""

    department_uuid: str
    r"""UUID of an existing company department"""


class PostV1CompaniesCompanyIDPeopleBatchesPaymentUnit(str, Enum):
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be `Paycheck`."""

    HOUR = "Hour"
    WEEK = "Week"
    MONTH = "Month"
    YEAR = "Year"
    PAYCHECK = "Paycheck"


class FlsaStatus(str, Enum):
    r"""The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ( 'Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company. If selecting `Owner`, `payment_unit` must be `\"Paycheck\"`."""

    EXEMPT = "Exempt"
    SALARIED_NONEXEMPT = "Salaried Nonexempt"
    NONEXEMPT = "Nonexempt"
    OWNER = "Owner"
    COMMISSION_ONLY_EXEMPT = "Commission Only Exempt"
    COMMISSION_ONLY_NONEXEMPT = "Commission Only Nonexempt"


class PostV1CompaniesCompanyIDPeopleBatchesCompensationTypedDict(TypedDict):
    r"""Compensation details for the employee (requires job to be provided)"""

    rate: str
    r"""The dollar amount paid per payment unit."""
    payment_unit: PostV1CompaniesCompanyIDPeopleBatchesPaymentUnit
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be `Paycheck`."""
    flsa_status: FlsaStatus
    r"""The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ( 'Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company. If selecting `Owner`, `payment_unit` must be `\"Paycheck\"`."""


class PostV1CompaniesCompanyIDPeopleBatchesCompensation(BaseModel):
    r"""Compensation details for the employee (requires job to be provided)"""

    rate: str
    r"""The dollar amount paid per payment unit."""

    payment_unit: PostV1CompaniesCompanyIDPeopleBatchesPaymentUnit
    r"""The unit accompanying the compensation rate. If the employee is an owner, rate should be `Paycheck`."""

    flsa_status: FlsaStatus
    r"""The FLSA status for this compensation. Salaried ('Exempt') employees are paid a fixed salary every pay period. Salaried with overtime ('Salaried Nonexempt') employees are paid a fixed salary every pay period, and receive overtime pay when applicable. Hourly ( 'Nonexempt') employees are paid for the hours they work, and receive overtime pay when applicable. Commissioned employees ('Commission Only Exempt') earn wages based only on commission. Commissioned with overtime ('Commission Only Nonexempt') earn wages based on commission, and receive overtime pay when applicable. Owners ('Owner') are employees that own at least twenty percent of the company. If selecting `Owner`, `payment_unit` must be `\"Paycheck\"`."""


class PostV1CompaniesCompanyIDPeopleBatchesAccountType(str, Enum):
    r"""Type of bank account"""

    CHECKING = "Checking"
    SAVINGS = "Savings"


class PostV1CompaniesCompanyIDPeopleBatchesType(str, Enum):
    r"""Payment type (must be Direct Deposit)"""

    DIRECT_DEPOSIT = "Direct Deposit"


class PostV1CompaniesCompanyIDPeopleBatchesSplitBy(str, Enum):
    r"""How to split deposits, must be the same for all bank accounts. If split_by is `Percentage`, then the split_amounts must add up to exactly 100."""

    AMOUNT = "Amount"
    PERCENTAGE = "Percentage"


class PostV1CompaniesCompanyIDPeopleBatchesBankAccountsTypedDict(TypedDict):
    account_type: PostV1CompaniesCompanyIDPeopleBatchesAccountType
    r"""Type of bank account"""
    routing_number: str
    r"""Bank routing number"""
    account_number: str
    r"""Bank account number"""
    type: PostV1CompaniesCompanyIDPeopleBatchesType
    r"""Payment type (must be Direct Deposit)"""
    split_by: PostV1CompaniesCompanyIDPeopleBatchesSplitBy
    r"""How to split deposits, must be the same for all bank accounts. If split_by is `Percentage`, then the split_amounts must add up to exactly 100."""
    name: NotRequired[Nullable[str]]
    r"""Account nickname"""
    split_amount: NotRequired[Nullable[str]]
    r"""Split amount in percentage or CENTS (`null` for remainder account)"""


class PostV1CompaniesCompanyIDPeopleBatchesBankAccounts(BaseModel):
    account_type: PostV1CompaniesCompanyIDPeopleBatchesAccountType
    r"""Type of bank account"""

    routing_number: str
    r"""Bank routing number"""

    account_number: str
    r"""Bank account number"""

    type: PostV1CompaniesCompanyIDPeopleBatchesType
    r"""Payment type (must be Direct Deposit)"""

    split_by: PostV1CompaniesCompanyIDPeopleBatchesSplitBy
    r"""How to split deposits, must be the same for all bank accounts. If split_by is `Percentage`, then the split_amounts must add up to exactly 100."""

    name: OptionalNullable[str] = UNSET
    r"""Account nickname"""

    split_amount: OptionalNullable[str] = UNSET
    r"""Split amount in percentage or CENTS (`null` for remainder account)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "split_amount"])
        nullable_fields = set(["name", "split_amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class BatchTypedDict(TypedDict):
    entity_type: PostV1CompaniesCompanyIDPeopleBatchesEntityType
    r"""The type of entity to create"""
    person: PersonTypedDict
    home_address: NotRequired[PostV1CompaniesCompanyIDPeopleBatchesHomeAddressTypedDict]
    r"""Home address for the employee"""
    work_address: NotRequired[PostV1CompaniesCompanyIDPeopleBatchesWorkAddressTypedDict]
    r"""Specify the company work location for the employee"""
    job: NotRequired[PostV1CompaniesCompanyIDPeopleBatchesJobTypedDict]
    r"""Job details for the employee (required if compensation is provided)"""
    department: NotRequired[PostV1CompaniesCompanyIDPeopleBatchesDepartmentTypedDict]
    r"""Department details for the employee"""
    compensation: NotRequired[
        PostV1CompaniesCompanyIDPeopleBatchesCompensationTypedDict
    ]
    r"""Compensation details for the employee (requires job to be provided)"""
    bank_accounts: NotRequired[
        List[PostV1CompaniesCompanyIDPeopleBatchesBankAccountsTypedDict]
    ]
    r"""Creates employee bank account(s) and payment method(s) for direct deposit. Payments can be split across accounts by Percentage or by Amount. If splitting payments by `Percentage`, all splits must have a `split_amount` and the percentages must add up to `100`.
    If splitting payments by `Amount`, the priority is set based on the order of the bank accounts in the array and the last bank account is the remainder account (should have `split_amount` set to `null`).
    """


class Batch(BaseModel):
    entity_type: PostV1CompaniesCompanyIDPeopleBatchesEntityType
    r"""The type of entity to create"""

    person: Person

    home_address: Optional[PostV1CompaniesCompanyIDPeopleBatchesHomeAddress] = None
    r"""Home address for the employee"""

    work_address: Optional[PostV1CompaniesCompanyIDPeopleBatchesWorkAddress] = None
    r"""Specify the company work location for the employee"""

    job: Optional[PostV1CompaniesCompanyIDPeopleBatchesJob] = None
    r"""Job details for the employee (required if compensation is provided)"""

    department: Optional[PostV1CompaniesCompanyIDPeopleBatchesDepartment] = None
    r"""Department details for the employee"""

    compensation: Optional[PostV1CompaniesCompanyIDPeopleBatchesCompensation] = None
    r"""Compensation details for the employee (requires job to be provided)"""

    bank_accounts: Optional[List[PostV1CompaniesCompanyIDPeopleBatchesBankAccounts]] = (
        None
    )
    r"""Creates employee bank account(s) and payment method(s) for direct deposit. Payments can be split across accounts by Percentage or by Amount. If splitting payments by `Percentage`, all splits must have a `split_amount` and the percentages must add up to `100`.
    If splitting payments by `Amount`, the priority is set based on the order of the bank accounts in the array and the last bank account is the remainder account (should have `split_amount` set to `null`).
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "home_address",
                "work_address",
                "job",
                "department",
                "compensation",
                "bank_accounts",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostV1CompaniesCompanyIDPeopleBatchesRequestBodyTypedDict(TypedDict):
    idempotency_key: str
    r"""A unique identifier to ensure idempotency of the batch request"""
    batch_action: BatchAction
    r"""The action to perform on the batch"""
    batch: List[BatchTypedDict]
    r"""Array of people to create"""


class PostV1CompaniesCompanyIDPeopleBatchesRequestBody(BaseModel):
    idempotency_key: str
    r"""A unique identifier to ensure idempotency of the batch request"""

    batch_action: BatchAction
    r"""The action to perform on the batch"""

    batch: List[Batch]
    r"""Array of people to create"""


class PostV1CompaniesCompanyIDPeopleBatchesRequestTypedDict(TypedDict):
    company_id: str
    r"""The UUID of the company"""
    body: PostV1CompaniesCompanyIDPeopleBatchesRequestBodyTypedDict
    x_gusto_api_version: NotRequired[
        PostV1CompaniesCompanyIDPeopleBatchesHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class PostV1CompaniesCompanyIDPeopleBatchesRequest(BaseModel):
    company_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    body: Annotated[
        PostV1CompaniesCompanyIDPeopleBatchesRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[PostV1CompaniesCompanyIDPeopleBatchesHeaderXGustoAPIVersion],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PostV1CompaniesCompanyIDPeopleBatchesHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_11_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PostV1CompaniesCompanyIDPeopleBatchesHomeAddress.model_rebuild()
except NameError:
    pass
