"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Category(str, Enum):
    r"""The category of the company attachment"""

    GEP_NOTICE = "gep_notice"
    COMPLIANCE = "compliance"
    OTHER = "other"


class CompanyAttachmentTypedDict(TypedDict):
    r"""The company attachment"""

    uuid: NotRequired[str]
    r"""UUID of the company attachment"""
    name: NotRequired[str]
    r"""name of the file uploaded"""
    category: NotRequired[Category]
    r"""The category of the company attachment"""
    upload_time: NotRequired[str]
    r"""The ISO 8601 timestamp of when an attachment was uploaded"""


class CompanyAttachment(BaseModel):
    r"""The company attachment"""

    uuid: Optional[str] = None
    r"""UUID of the company attachment"""

    name: Optional[str] = None
    r"""name of the file uploaded"""

    category: Optional[Category] = None
    r"""The category of the company attachment"""

    upload_time: Optional[str] = None
    r"""The ISO 8601 timestamp of when an attachment was uploaded"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uuid", "name", "category", "upload_time"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
