"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ReconcileTaxMethod(str, Enum):
    r"""How Gusto will handle taxes already collected."""

    PAY_TAXES = "pay_taxes"
    REFUND_TAXES = "refund_taxes"


class TaxRefundsTypedDict(TypedDict):
    amount: NotRequired[str]
    r"""Dollar amount."""
    description: NotRequired[str]
    r"""What kind of tax this is."""


class TaxRefunds(BaseModel):
    amount: Optional[str] = None
    r"""Dollar amount."""

    description: Optional[str] = None
    r"""What kind of tax this is."""


class CompanySuspensionTypedDict(TypedDict):
    r"""Record representing the suspension of a company's Gusto account."""

    uuid: NotRequired[str]
    r"""Unique identifier for this suspension."""
    company_uuid: NotRequired[str]
    r"""Unique identifier for the company which is suspended."""
    effective_date: NotRequired[str]
    r"""Date that the suspension took effect."""
    leaving_for: NotRequired[Nullable[str]]
    r"""Which competitor the company is joining instead. Only required if `reason` is `'switching_provider'`."""
    reason: NotRequired[str]
    r"""Explanation for why the company's account was suspended."""
    reconcile_tax_method: NotRequired[ReconcileTaxMethod]
    r"""How Gusto will handle taxes already collected."""
    file_quarterly_forms: NotRequired[bool]
    r"""Should Gusto file quarterly tax forms on behalf of the company? The correct answer can depend on why the company is suspending their account, and how taxes are being reconciled.

    """
    file_yearly_forms: NotRequired[bool]
    r"""Should Gusto file yearly tax forms on behalf of the company? The correct answer can depend on why the company is suspending their account, and how taxes are being reconciled.

    """
    comments: NotRequired[Nullable[str]]
    r"""User-supplied comments describing why they are suspending their account."""
    tax_refunds: NotRequired[List[TaxRefundsTypedDict]]
    r"""Describes the taxes which are refundable to the company for this suspension. These may be refunded or paid by Gusto depending on the value in `reconcile_tax_method`.

    """


class CompanySuspension(BaseModel):
    r"""Record representing the suspension of a company's Gusto account."""

    uuid: Optional[str] = None
    r"""Unique identifier for this suspension."""

    company_uuid: Optional[str] = None
    r"""Unique identifier for the company which is suspended."""

    effective_date: Optional[str] = None
    r"""Date that the suspension took effect."""

    leaving_for: OptionalNullable[str] = UNSET
    r"""Which competitor the company is joining instead. Only required if `reason` is `'switching_provider'`."""

    reason: Optional[str] = None
    r"""Explanation for why the company's account was suspended."""

    reconcile_tax_method: Optional[ReconcileTaxMethod] = None
    r"""How Gusto will handle taxes already collected."""

    file_quarterly_forms: Optional[bool] = None
    r"""Should Gusto file quarterly tax forms on behalf of the company? The correct answer can depend on why the company is suspending their account, and how taxes are being reconciled.

    """

    file_yearly_forms: Optional[bool] = None
    r"""Should Gusto file yearly tax forms on behalf of the company? The correct answer can depend on why the company is suspending their account, and how taxes are being reconciled.

    """

    comments: OptionalNullable[str] = UNSET
    r"""User-supplied comments describing why they are suspending their account."""

    tax_refunds: Optional[List[TaxRefunds]] = None
    r"""Describes the taxes which are refundable to the company for this suspension. These may be refunded or paid by Gusto depending on the value in `reconcile_tax_method`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "uuid",
            "company_uuid",
            "effective_date",
            "leaving_for",
            "reason",
            "reconcile_tax_method",
            "file_quarterly_forms",
            "file_yearly_forms",
            "comments",
            "tax_refunds",
        ]
        nullable_fields = ["leaving_for", "comments"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
