"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ContractorsSortBy(str, Enum):
    TYPE = "type"
    ONBOARDING_STATUS = "onboarding_status"
    NAME = "name"
    CREATED_AT = "created_at"
