"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ContractorUpdateRequestBodyType(str, Enum):
    r"""The contractor type."""

    INDIVIDUAL = "Individual"
    BUSINESS = "Business"


class ContractorUpdateRequestBodyWageType(str, Enum):
    r"""The contractor’s wage type."""

    FIXED = "Fixed"
    HOURLY = "Hourly"


class ContractorUpdateRequestBodyTypedDict(TypedDict):
    r"""Request body for updating a contractor."""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""
    type: NotRequired[ContractorUpdateRequestBodyType]
    r"""The contractor type."""
    wage_type: NotRequired[ContractorUpdateRequestBodyWageType]
    r"""The contractor’s wage type.

    """
    start_date: NotRequired[str]
    r"""The day when the contractor will start working for the company.

    """
    hourly_rate: NotRequired[str]
    r"""The contractor’s hourly rate. This attribute is required if the wage_type is `Hourly`."""
    self_onboarding: NotRequired[bool]
    r"""Whether the contractor or the payroll admin will complete onboarding in Gusto.
    Self-onboarding is recommended so that contractors receive Gusto accounts.
    If self_onboarding is true, then email is required.
    """
    email: NotRequired[str]
    r"""The contractor’s email address."""
    first_name: NotRequired[str]
    r"""The contractor’s first name.
    This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    """
    last_name: NotRequired[str]
    r"""The contractor’s last name.
    This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    """
    middle_initial: NotRequired[str]
    r"""The contractor’s middle initial.
    This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    """
    file_new_hire_report: NotRequired[bool]
    r"""The boolean flag indicating whether Gusto will file a new hire report for the contractor.
    This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    """
    work_state: NotRequired[Nullable[str]]
    r"""State where the contractor will be conducting the majority of their work for the company.
    This value is used when generating the new hire report.
    This attribute is required for `Individual` contractors if `file_new_hire_report` is true and will be ignored for `Business` contractors.
    """
    ssn: NotRequired[str]
    r"""This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    Social security number is needed to file the annual 1099 tax form.
    """
    business_name: NotRequired[str]
    r"""The name of the contractor business. This attribute is required for `Business` contractors and will be ignored for `Individual` contractors."""
    ein: NotRequired[str]
    r"""The employer identification number of the contractor business.
    This attribute is optional for `Business` contractors and will be ignored for `Individual` contractors.
    """
    is_active: NotRequired[bool]
    r"""The status of the contractor. If the contractor's start date is in the future, updating this field to true means we are setting the start date to today."""


class ContractorUpdateRequestBody(BaseModel):
    r"""Request body for updating a contractor."""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""

    type: Optional[ContractorUpdateRequestBodyType] = (
        ContractorUpdateRequestBodyType.INDIVIDUAL
    )
    r"""The contractor type."""

    wage_type: Optional[ContractorUpdateRequestBodyWageType] = None
    r"""The contractor’s wage type.

    """

    start_date: Optional[str] = None
    r"""The day when the contractor will start working for the company.

    """

    hourly_rate: Optional[str] = None
    r"""The contractor’s hourly rate. This attribute is required if the wage_type is `Hourly`."""

    self_onboarding: Optional[bool] = False
    r"""Whether the contractor or the payroll admin will complete onboarding in Gusto.
    Self-onboarding is recommended so that contractors receive Gusto accounts.
    If self_onboarding is true, then email is required.
    """

    email: Optional[str] = None
    r"""The contractor’s email address."""

    first_name: Optional[str] = None
    r"""The contractor’s first name.
    This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    """

    last_name: Optional[str] = None
    r"""The contractor’s last name.
    This attribute is required for `Individual` contractors and will be ignored for `Business` contractors.
    """

    middle_initial: Optional[str] = None
    r"""The contractor’s middle initial.
    This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    """

    file_new_hire_report: Optional[bool] = False
    r"""The boolean flag indicating whether Gusto will file a new hire report for the contractor.
    This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    """

    work_state: OptionalNullable[str] = UNSET
    r"""State where the contractor will be conducting the majority of their work for the company.
    This value is used when generating the new hire report.
    This attribute is required for `Individual` contractors if `file_new_hire_report` is true and will be ignored for `Business` contractors.
    """

    ssn: Optional[str] = None
    r"""This attribute is optional for `Individual` contractors and will be ignored for `Business` contractors.
    Social security number is needed to file the annual 1099 tax form.
    """

    business_name: Optional[str] = None
    r"""The name of the contractor business. This attribute is required for `Business` contractors and will be ignored for `Individual` contractors."""

    ein: Optional[str] = None
    r"""The employer identification number of the contractor business.
    This attribute is optional for `Business` contractors and will be ignored for `Individual` contractors.
    """

    is_active: Optional[bool] = None
    r"""The status of the contractor. If the contractor's start date is in the future, updating this field to true means we are setting the start date to today."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "type",
                "wage_type",
                "start_date",
                "hourly_rate",
                "self_onboarding",
                "email",
                "first_name",
                "last_name",
                "middle_initial",
                "file_new_hire_report",
                "work_state",
                "ssn",
                "business_name",
                "ein",
                "is_active",
            ]
        )
        nullable_fields = set(["work_state"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
