"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ValueTypedDict = TypeAliasType("ValueTypedDict", Union[str, float, bool])
r"""The answer to the corresponding question - this may be a string, number, boolean, or null."""


Value = TypeAliasType("Value", Union[str, float, bool])
r"""The answer to the corresponding question - this may be a string, number, boolean, or null."""


class EmployeeStateTaxAnswerTypedDict(TypedDict):
    value: NotRequired[Nullable[ValueTypedDict]]
    r"""The answer to the corresponding question - this may be a string, number, boolean, or null."""
    valid_from: NotRequired[str]
    r"""The effective date of the answer - currently always “2010-01-01”."""
    valid_up_to: NotRequired[Nullable[str]]
    r"""The effective end date of the answer - currently always null."""


class EmployeeStateTaxAnswer(BaseModel):
    value: OptionalNullable[Value] = UNSET
    r"""The answer to the corresponding question - this may be a string, number, boolean, or null."""

    valid_from: Optional[str] = None
    r"""The effective date of the answer - currently always “2010-01-01”."""

    valid_up_to: OptionalNullable[str] = UNSET
    r"""The effective end date of the answer - currently always null."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["value", "valid_from", "valid_up_to"])
        nullable_fields = set(["value", "valid_up_to"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
