"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from enum import Enum
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class EmployeeBenefitUpdateRequestType(str, Enum):
    r"""The company contribution scheme.

    `amount`: The company contributes a fixed amount per payroll. If elective is true, the contribution is matching, dollar-for-dollar.

    `percentage`: The company contributes a percentage of the payroll amount per payroll period. If elective is true, the contribution is matching, dollar-for-dollar.

    `tiered`: The size of the company contribution corresponds to the size of the employee deduction relative to a tiered matching scheme.
    """

    AMOUNT = "amount"
    PERCENTAGE = "percentage"
    TIERED = "tiered"


class EmployeeBenefitUpdateRequestValue2TypedDict(TypedDict):
    r"""A single tier of a tiered matching scheme."""

    rate: NotRequired[str]
    r"""The percentage of employee deduction within this tier the company contribution will match."""
    threshold: NotRequired[str]
    r"""Specifies the upper limit (inclusive) percentage of the employee contribution that this tier applies to.

    Use threshold to define each tier's end point, with tiers applied cumulatively from 0% upwards.

    For example:

    If the first tier has a threshold of \"3\", and rate of \"100\", the company will match 100% of employee contributions from 0% up to and including 3% of payroll.

    If the next tier has a threshold of \"5\" and a rate of \"50\", the company will match 50% of contributions from above 3% up to and including 5% of payroll.
    """


class EmployeeBenefitUpdateRequestValue2(BaseModel):
    r"""A single tier of a tiered matching scheme."""

    rate: Optional[str] = None
    r"""The percentage of employee deduction within this tier the company contribution will match."""

    threshold: Optional[str] = None
    r"""Specifies the upper limit (inclusive) percentage of the employee contribution that this tier applies to.

    Use threshold to define each tier's end point, with tiers applied cumulatively from 0% upwards.

    For example:

    If the first tier has a threshold of \"3\", and rate of \"100\", the company will match 100% of employee contributions from 0% up to and including 3% of payroll.

    If the next tier has a threshold of \"5\" and a rate of \"50\", the company will match 50% of contributions from above 3% up to and including 5% of payroll.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rate", "threshold"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


EmployeeBenefitUpdateRequestValueTypedDict = TypeAliasType(
    "EmployeeBenefitUpdateRequestValueTypedDict",
    Union[str, List[EmployeeBenefitUpdateRequestValue2TypedDict]],
)
r"""For the `amount` and `percentage` contribution types, the value of the corresponding amount or percentage.

For the `tiered` contribution type, an array of tiers.
"""


EmployeeBenefitUpdateRequestValue = TypeAliasType(
    "EmployeeBenefitUpdateRequestValue",
    Union[str, List[EmployeeBenefitUpdateRequestValue2]],
)
r"""For the `amount` and `percentage` contribution types, the value of the corresponding amount or percentage.

For the `tiered` contribution type, an array of tiers.
"""


class EmployeeBenefitUpdateRequestContributionTypedDict(TypedDict):
    r"""An object representing the type and value of the company contribution."""

    type: NotRequired[EmployeeBenefitUpdateRequestType]
    r"""The company contribution scheme.

    `amount`: The company contributes a fixed amount per payroll. If elective is true, the contribution is matching, dollar-for-dollar.

    `percentage`: The company contributes a percentage of the payroll amount per payroll period. If elective is true, the contribution is matching, dollar-for-dollar.

    `tiered`: The size of the company contribution corresponds to the size of the employee deduction relative to a tiered matching scheme.
    """
    value: NotRequired[EmployeeBenefitUpdateRequestValueTypedDict]
    r"""For the `amount` and `percentage` contribution types, the value of the corresponding amount or percentage.

    For the `tiered` contribution type, an array of tiers.
    """


class EmployeeBenefitUpdateRequestContribution(BaseModel):
    r"""An object representing the type and value of the company contribution."""

    type: Optional[EmployeeBenefitUpdateRequestType] = None
    r"""The company contribution scheme.

    `amount`: The company contributes a fixed amount per payroll. If elective is true, the contribution is matching, dollar-for-dollar.

    `percentage`: The company contributes a percentage of the payroll amount per payroll period. If elective is true, the contribution is matching, dollar-for-dollar.

    `tiered`: The size of the company contribution corresponds to the size of the employee deduction relative to a tiered matching scheme.
    """

    value: Optional[EmployeeBenefitUpdateRequestValue] = None
    r"""For the `amount` and `percentage` contribution types, the value of the corresponding amount or percentage.

    For the `tiered` contribution type, an array of tiers.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EmployeeBenefitUpdateRequestLimitOption(str, Enum):
    r"""Some benefits require additional information to determine
    their limit.

    `Family` or `Individual`: Applicable to HSA benefit.

    `Joint Filing or Single` or `Married and Filing Separately`: Applicable to Dependent Care FSA benefit.
    """

    FAMILY = "Family"
    INDIVIDUAL = "Individual"
    JOINT_FILING_OR_SINGLE = "Joint Filing or Single"
    MARRIED_AND_FILING_SEPARATELY = "Married and Filing Separately"


class EmployeeBenefitUpdateRequestDeductionReducesTaxableIncome(str, Enum):
    r"""Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life benefits. Note: when the value is not \"unset\", coverage amount and coverage salary multiplier are ignored."""

    UNSET = "unset"
    REDUCES_TAXABLE_INCOME = "reduces_taxable_income"
    DOES_NOT_REDUCE_TAXABLE_INCOME = "does_not_reduce_taxable_income"


class EmployeeBenefitUpdateRequestTypedDict(TypedDict):
    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field."""
    active: NotRequired[bool]
    r"""Whether the employee benefit is active."""
    employee_deduction: NotRequired[str]
    r"""The amount to be deducted, per pay period, from the employee's pay."""
    deduct_as_percentage: NotRequired[bool]
    r"""Whether the employee deduction amount should be treated as a percentage to be deducted from each payroll."""
    employee_deduction_annual_maximum: NotRequired[Nullable[str]]
    r"""The maximum employee deduction amount per year. A null value signifies no limit."""
    effective_date: NotRequired[date]
    r"""The date the employee benefit will start."""
    expiration_date: NotRequired[Nullable[date]]
    r"""The date the employee benefit will expire. A null value indicates the benefit will not expire."""
    contribution: NotRequired[EmployeeBenefitUpdateRequestContributionTypedDict]
    r"""An object representing the type and value of the company contribution."""
    elective: NotRequired[bool]
    r"""Whether the company contribution is elective (aka \"matching\"). For `tiered`, `elective_amount`, and `elective_percentage` contribution types this is ignored and assumed to be `true`."""
    company_contribution_annual_maximum: NotRequired[Nullable[str]]
    r"""The maximum company contribution amount per year. A null value signifies no limit."""
    limit_option: NotRequired[Nullable[EmployeeBenefitUpdateRequestLimitOption]]
    r"""Some benefits require additional information to determine
    their limit.

    `Family` or `Individual`: Applicable to HSA benefit.

    `Joint Filing or Single` or `Married and Filing Separately`: Applicable to Dependent Care FSA benefit.
    """
    catch_up: NotRequired[bool]
    r"""Whether the employee should use a benefit's \"catch up\" rate. Only Roth 401k and 401k benefits use this value for employees over 50."""
    coverage_amount: NotRequired[Nullable[str]]
    r"""The amount that the employee is insured for. Note: company contribution cannot be present if coverage amount is set."""
    deduction_reduces_taxable_income: NotRequired[
        Nullable[EmployeeBenefitUpdateRequestDeductionReducesTaxableIncome]
    ]
    r"""Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life benefits. Note: when the value is not \"unset\", coverage amount and coverage salary multiplier are ignored."""
    coverage_salary_multiplier: NotRequired[str]
    r"""The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life benefits. Note: cannot be set if coverage amount is also set."""
    company_contribution: NotRequired[str]
    r"""The amount to be paid, per pay period, by the company."""
    contribute_as_percentage: NotRequired[bool]
    r"""Whether the company contribution amount should be treated as a percentage to be deducted from each payroll."""


class EmployeeBenefitUpdateRequest(BaseModel):
    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field."""

    active: Optional[bool] = None
    r"""Whether the employee benefit is active."""

    employee_deduction: Optional[str] = "0.00"
    r"""The amount to be deducted, per pay period, from the employee's pay."""

    deduct_as_percentage: Optional[bool] = None
    r"""Whether the employee deduction amount should be treated as a percentage to be deducted from each payroll."""

    employee_deduction_annual_maximum: OptionalNullable[str] = UNSET
    r"""The maximum employee deduction amount per year. A null value signifies no limit."""

    effective_date: Optional[date] = None
    r"""The date the employee benefit will start."""

    expiration_date: OptionalNullable[date] = UNSET
    r"""The date the employee benefit will expire. A null value indicates the benefit will not expire."""

    contribution: Optional[EmployeeBenefitUpdateRequestContribution] = None
    r"""An object representing the type and value of the company contribution."""

    elective: Optional[bool] = False
    r"""Whether the company contribution is elective (aka \"matching\"). For `tiered`, `elective_amount`, and `elective_percentage` contribution types this is ignored and assumed to be `true`."""

    company_contribution_annual_maximum: OptionalNullable[str] = UNSET
    r"""The maximum company contribution amount per year. A null value signifies no limit."""

    limit_option: OptionalNullable[EmployeeBenefitUpdateRequestLimitOption] = UNSET
    r"""Some benefits require additional information to determine
    their limit.

    `Family` or `Individual`: Applicable to HSA benefit.

    `Joint Filing or Single` or `Married and Filing Separately`: Applicable to Dependent Care FSA benefit.
    """

    catch_up: Optional[bool] = False
    r"""Whether the employee should use a benefit's \"catch up\" rate. Only Roth 401k and 401k benefits use this value for employees over 50."""

    coverage_amount: OptionalNullable[str] = UNSET
    r"""The amount that the employee is insured for. Note: company contribution cannot be present if coverage amount is set."""

    deduction_reduces_taxable_income: OptionalNullable[
        EmployeeBenefitUpdateRequestDeductionReducesTaxableIncome
    ] = EmployeeBenefitUpdateRequestDeductionReducesTaxableIncome.UNSET
    r"""Whether the employee deduction reduces taxable income or not. Only valid for Group Term Life benefits. Note: when the value is not \"unset\", coverage amount and coverage salary multiplier are ignored."""

    coverage_salary_multiplier: Optional[str] = "0.00"
    r"""The coverage amount as a multiple of the employee's salary. Only applicable for Group Term Life benefits. Note: cannot be set if coverage amount is also set."""

    company_contribution: Annotated[
        Optional[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = "0.00"
    r"""The amount to be paid, per pay period, by the company."""

    contribute_as_percentage: Annotated[
        Optional[bool],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = False
    r"""Whether the company contribution amount should be treated as a percentage to be deducted from each payroll."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "active",
                "employee_deduction",
                "deduct_as_percentage",
                "employee_deduction_annual_maximum",
                "effective_date",
                "expiration_date",
                "contribution",
                "elective",
                "company_contribution_annual_maximum",
                "limit_option",
                "catch_up",
                "coverage_amount",
                "deduction_reduces_taxable_income",
                "coverage_salary_multiplier",
                "company_contribution",
                "contribute_as_percentage",
            ]
        )
        nullable_fields = set(
            [
                "employee_deduction_annual_maximum",
                "expiration_date",
                "company_contribution_annual_maximum",
                "limit_option",
                "coverage_amount",
                "deduction_reduces_taxable_income",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
