"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .versionheader import VersionHeader
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from gusto_embedded.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessRequestTypedDict(
    TypedDict
):
    company_uuid: str
    r"""The UUID of the company"""
    x_gusto_api_version: NotRequired[VersionHeader]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessRequest(BaseModel):
    company_uuid: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    x_gusto_api_version: Annotated[
        Optional[VersionHeader],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = VersionHeader.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessMetadataTypedDict(
    TypedDict
):
    key: NotRequired[str]
    r"""A categorization of the migration blocker, e.g. \"migrated_company\" """


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessMetadata(BaseModel):
    key: Optional[str] = None
    r"""A categorization of the migration blocker, e.g. \"migrated_company\" """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessErrorsTypedDict(
    TypedDict
):
    error_key: NotRequired[str]
    r"""Error key"""
    category: NotRequired[str]
    r"""Error category"""
    message: NotRequired[str]
    r"""Blocker message"""
    metadata: NotRequired[
        GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessMetadataTypedDict
    ]


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessErrors(BaseModel):
    error_key: Optional[str] = None
    r"""Error key"""

    category: Optional[str] = None
    r"""Error category"""

    message: Optional[str] = None
    r"""Blocker message"""

    metadata: Optional[
        GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessMetadata
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error_key", "category", "message", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessCompaniesMetadataTypedDict(
    TypedDict
):
    key: NotRequired[str]
    r"""A categorization of the migration warning, e.g. \"marijuana_related_business\" """


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessCompaniesMetadata(
    BaseModel
):
    key: Optional[str] = None
    r"""A categorization of the migration warning, e.g. \"marijuana_related_business\" """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WarningsTypedDict(TypedDict):
    error_key: NotRequired[str]
    r"""Error key"""
    category: NotRequired[str]
    r"""Error category"""
    message: NotRequired[str]
    r"""Warning message"""
    metadata: NotRequired[
        GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessCompaniesMetadataTypedDict
    ]


class Warnings(BaseModel):
    error_key: Optional[str] = None
    r"""Error key"""

    category: Optional[str] = None
    r"""Error category"""

    message: Optional[str] = None
    r"""Warning message"""

    metadata: Optional[
        GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessCompaniesMetadata
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["error_key", "category", "message", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessResponseBodyTypedDict(
    TypedDict
):
    r"""Example response"""

    ready_to_migrate: NotRequired[bool]
    r"""Indicates if the company is ready to be migrated."""
    company_uuid: NotRequired[str]
    r"""The company UUID"""
    errors: NotRequired[
        List[GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessErrorsTypedDict]
    ]
    warnings: NotRequired[List[WarningsTypedDict]]


class GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessResponseBody(BaseModel):
    r"""Example response"""

    ready_to_migrate: Optional[bool] = None
    r"""Indicates if the company is ready to be migrated."""

    company_uuid: Optional[str] = None
    r"""The company UUID"""

    errors: Optional[
        List[GetV1PartnerManagedCompaniesCompanyUUIDMigrationReadinessErrors]
    ] = None

    warnings: Optional[List[Warnings]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["ready_to_migrate", "company_uuid", "errors", "warnings"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
