"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class I9AuthorizationDocumentTypedDict(TypedDict):
    r"""An employee's I-9 verification document"""

    uuid: str
    r"""The UUID of the I-9 verification document"""
    document_type: str
    r"""The document's document type"""
    document_title: str
    r"""The document's document title"""
    issuing_authority: str
    r"""The document's issuing authority"""
    expiration_date: NotRequired[Nullable[str]]
    r"""The document's expiration date"""


class I9AuthorizationDocument(BaseModel):
    r"""An employee's I-9 verification document"""

    uuid: str
    r"""The UUID of the I-9 verification document"""

    document_type: str
    r"""The document's document type"""

    document_title: str
    r"""The document's document title"""

    issuing_authority: str
    r"""The document's issuing authority"""

    expiration_date: OptionalNullable[str] = UNSET
    r"""The document's expiration date"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expiration_date"])
        nullable_fields = set(["expiration_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
