"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import BaseModel
from gusto_embedded.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsHeaderXGustoAPIVersion(
    str, Enum
):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FOUR_MINUS_04_MINUS_01 = "2024-04-01"


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentMethod(str, Enum):
    r"""Payment method for the employee"""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentStatus(str, Enum):
    r"""Status of the payment disbursement"""

    PENDING = "Pending"
    PAID = "Paid"
    NOT_PARTNER_MANAGED = "Not partner managed"
    CONVERTED_TO_CHECK = "Converted to check"


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsDisbursementsTypedDict(
    TypedDict
):
    employee_uuid: str
    r"""UUID of the employee"""
    payment_method: NotRequired[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentMethod
    ]
    r"""Payment method for the employee"""
    payment_status: NotRequired[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentStatus
    ]
    r"""Status of the payment disbursement"""


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsDisbursements(BaseModel):
    employee_uuid: str
    r"""UUID of the employee"""

    payment_method: Optional[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentMethod
    ] = None
    r"""Payment method for the employee"""

    payment_status: Optional[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsPaymentStatus
    ] = None
    r"""Status of the payment disbursement"""


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequestBodyTypedDict(
    TypedDict
):
    disbursements: List[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsDisbursementsTypedDict
    ]


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequestBody(BaseModel):
    disbursements: List[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsDisbursements
    ]


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequestTypedDict(
    TypedDict
):
    company_id: str
    r"""The UUID of the company"""
    id: str
    r"""The UUID of the payroll"""
    x_gusto_api_version: NotRequired[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""
    request_body: NotRequired[
        PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequestBodyTypedDict
    ]


class PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequest(BaseModel):
    company_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the payroll"""

    x_gusto_api_version: Annotated[
        Optional[
            PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsHeaderXGustoAPIVersion
        ],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FOUR_MINUS_04_MINUS_01
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    request_body: Annotated[
        Optional[PatchV1CompaniesCompanyIDPayrollsIDPartnerDisbursementsRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
