"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class HoursEarnedTypedDict(TypedDict):
    time_off_policy_uuid: NotRequired[str]
    r"""The UUID of the time off policy"""
    hours: NotRequired[str]
    r"""Hours accrued during this pay period."""


class HoursEarned(BaseModel):
    time_off_policy_uuid: Optional[str] = None
    r"""The UUID of the time off policy"""

    hours: Optional[str] = None
    r"""Hours accrued during this pay period."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["time_off_policy_uuid", "hours"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayrollCalculateAccruingTimeOffHoursResponseTypedDict(TypedDict):
    r"""Response containing the calculated accruing time off hours"""

    hours_earned: List[HoursEarnedTypedDict]
    r"""Accruing time off hours earned for each time off policy"""


class PayrollCalculateAccruingTimeOffHoursResponse(BaseModel):
    r"""Response containing the calculated accruing time off hours"""

    hours_earned: List[HoursEarned]
    r"""Accruing time off hours earned for each time off policy"""
