"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PayrollPartnerDisbursementsPaymentMethod(str, Enum):
    r"""The payment method for the disbursement"""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"


class PayrollPartnerDisbursementsPaymentStatus(str, Enum):
    r"""The status of the payment"""

    PENDING = "Pending"
    PAID = "Paid"
    NOT_PARTNER_MANAGED = "Not partner managed"
    CONVERTED_TO_CHECK = "Converted to check"


class PayrollPartnerDisbursementsDisbursementsTypedDict(TypedDict):
    employee_uuid: NotRequired[str]
    r"""The UUID of the employee"""
    payment_method: NotRequired[PayrollPartnerDisbursementsPaymentMethod]
    r"""The payment method for the disbursement"""
    payment_status: NotRequired[PayrollPartnerDisbursementsPaymentStatus]
    r"""The status of the payment"""


class PayrollPartnerDisbursementsDisbursements(BaseModel):
    employee_uuid: Optional[str] = None
    r"""The UUID of the employee"""

    payment_method: Optional[PayrollPartnerDisbursementsPaymentMethod] = None
    r"""The payment method for the disbursement"""

    payment_status: Optional[PayrollPartnerDisbursementsPaymentStatus] = None
    r"""The status of the payment"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["employee_uuid", "payment_method", "payment_status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayrollPartnerDisbursementsTypedDict(TypedDict):
    r"""Partner disbursements for a payroll"""

    payroll_uuid: NotRequired[str]
    r"""The UUID of the payroll"""
    disbursements: NotRequired[List[PayrollPartnerDisbursementsDisbursementsTypedDict]]
    r"""List of disbursements for the payroll"""


class PayrollPartnerDisbursements(BaseModel):
    r"""Partner disbursements for a payroll"""

    payroll_uuid: Optional[str] = None
    r"""The UUID of the payroll"""

    disbursements: Optional[List[PayrollPartnerDisbursementsDisbursements]] = None
    r"""List of disbursements for the payroll"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["payroll_uuid", "disbursements"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
