"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import BaseModel
from typing_extensions import TypedDict


class PeopleBatchStatus(str, Enum):
    r"""The current status of the batch processing."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    PARTIAL_SUCCESS = "partial_success"


class PeopleBatchTypedDict(TypedDict):
    r"""A batch for bulk people creation."""

    uuid: str
    r"""The unique identifier of the people batch."""
    idempotency_key: str
    r"""The idempotency key provided when creating the batch."""
    status: PeopleBatchStatus
    r"""The current status of the batch processing."""
    batch_action: str
    r"""The action being performed on the batch."""


class PeopleBatch(BaseModel):
    r"""A batch for bulk people creation."""

    uuid: str
    r"""The unique identifier of the people batch."""

    idempotency_key: str
    r"""The idempotency key provided when creating the batch."""

    status: PeopleBatchStatus
    r"""The current status of the batch processing."""

    batch_action: str
    r"""The action being performed on the batch."""
