"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from enum import Enum
from gusto_embedded.types import BaseModel
from gusto_embedded.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewHeaderXGustoAPIVersion(
    str, Enum
):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15 = "2025-06-15"


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewPaymentMethod(str, Enum):
    r"""Payment method"""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewContractorPaymentsTypedDict(
    TypedDict
):
    contractor_uuid: NotRequired[str]
    r"""UUID of the contractor"""
    payment_method: NotRequired[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewPaymentMethod
    ]
    r"""Payment method"""
    wage: NotRequired[float]
    r"""Wage amount"""
    reimbursement: NotRequired[float]
    r"""Reimbursement amount"""


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewContractorPayments(
    BaseModel
):
    contractor_uuid: Optional[str] = None
    r"""UUID of the contractor"""

    payment_method: Optional[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewPaymentMethod
    ] = None
    r"""Payment method"""

    wage: Optional[float] = None
    r"""Wage amount"""

    reimbursement: Optional[float] = None
    r"""Reimbursement amount"""


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequestBodyTypedDict(
    TypedDict
):
    contractor_payments: List[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewContractorPaymentsTypedDict
    ]
    check_date: NotRequired[date]
    r"""Date when payments should be processed"""


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequestBody(BaseModel):
    contractor_payments: List[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewContractorPayments
    ]

    check_date: Optional[date] = None
    r"""Date when payments should be processed"""


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequestTypedDict(TypedDict):
    company_id: str
    r"""The UUID of the company"""
    request_body: (
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequestBodyTypedDict
    )
    x_gusto_api_version: NotRequired[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequest(BaseModel):
    company_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    request_body: Annotated[
        PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[
            PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewHeaderXGustoAPIVersion
        ],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PostV1CompaniesCompanyIDContractorPaymentGroupsPreviewHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""
