"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .employee_section603_high_earner_status_create_request import (
    EmployeeSection603HighEarnerStatusCreateRequest,
    EmployeeSection603HighEarnerStatusCreateRequestTypedDict,
)
from enum import Enum
from gusto_embedded.types import BaseModel
from gusto_embedded.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesHeaderXGustoAPIVersion(
    str, Enum
):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FOUR_MINUS_04_MINUS_01 = "2024-04-01"


class PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesRequestTypedDict(
    TypedDict
):
    employee_uuid: str
    r"""The UUID of the employee"""
    employee_section603_high_earner_status_create_request: (
        EmployeeSection603HighEarnerStatusCreateRequestTypedDict
    )
    x_gusto_api_version: NotRequired[
        PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesRequest(BaseModel):
    employee_uuid: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the employee"""

    employee_section603_high_earner_status_create_request: Annotated[
        EmployeeSection603HighEarnerStatusCreateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[
            PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesHeaderXGustoAPIVersion
        ],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PostV1EmployeesEmployeeUUIDSection603HighEarnerStatusesHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FOUR_MINUS_04_MINUS_01
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""
