"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from gusto_embedded.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveHeaderXGustoAPIVersion(str, Enum):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15 = "2025-06-15"


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveEmployeesTypedDict(TypedDict):
    uuid: NotRequired[str]


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveEmployees(BaseModel):
    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequestBodyTypedDict(TypedDict):
    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""
    employees: List[PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveEmployeesTypedDict]
    r"""An array of employee objects, each containing an employee_uuid."""


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequestBody(BaseModel):
    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""

    employees: List[PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveEmployees]
    r"""An array of employee objects, each containing an employee_uuid."""


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequestTypedDict(TypedDict):
    company_uuid: str
    r"""The UUID of the company"""
    request_body: PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequestBodyTypedDict
    x_gusto_api_version: NotRequired[
        PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveHeaderXGustoAPIVersion
    ]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequest(BaseModel):
    company_uuid: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the company"""

    request_body: Annotated[
        PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveHeaderXGustoAPIVersion],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PutV1CompaniesCompanyUUIDHolidayPayPolicyRemoveHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
