"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ReportTemplateTypedDict(TypedDict):
    columns: NotRequired[List[str]]
    r"""List of columns recommended"""
    groupings: NotRequired[List[str]]
    r"""List of groupings recommended"""
    company_uuid: NotRequired[str]
    r"""Company UUID"""
    report_type: NotRequired[str]
    r"""Type of report template"""


class ReportTemplate(BaseModel):
    columns: Optional[List[str]] = None
    r"""List of columns recommended"""

    groupings: Optional[List[str]] = None
    r"""List of groupings recommended"""

    company_uuid: Optional[str] = None
    r"""Company UUID"""

    report_type: Optional[str] = None
    r"""Type of report template"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["columns", "groupings", "company_uuid", "report_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
