"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ReverseWireTransactionStatus(str, Enum):
    r"""Current status of the reverse wire transaction.
    - `pending_processing`: The reverse wire has been initiated and is awaiting processing by the banking network.
    - `processed`: The reverse wire was successfully settled and funds have been received.
    - `rejected`: The reverse wire was rejected by the receiving bank (e.g. invalid account, insufficient funds).
    - `failed`: The reverse wire failed during processing due to a system or network error.

    """

    PENDING_PROCESSING = "pending_processing"
    PROCESSED = "processed"
    REJECTED = "rejected"
    FAILED = "failed"


class ReverseWireTransactionPaymentDirection(str, Enum):
    r"""The direction of the payment. Reverse wires are always debits from the company's account."""

    DEBIT = "debit"


class ReverseWireTransactionPaymentEventType(str, Enum):
    PAYROLL = "Payroll"
    CONTRACTOR_PAYMENT = "ContractorPayment"


class ReverseWireTransactionTypedDict(TypedDict):
    r"""Representation of a reverse wire (drawdown) transaction. Reverse wires are debit transactions initiated by Gusto to pull funds from a partner's bank account to cover payroll or contractor payment obligations."""

    company_uuid: str
    r"""Unique identifier of the company the reverse wire transaction belongs to"""
    amount: str
    r"""The amount of money moved by the reverse wire, as a decimal string. Always non-negative."""
    status: ReverseWireTransactionStatus
    r"""Current status of the reverse wire transaction.
    - `pending_processing`: The reverse wire has been initiated and is awaiting processing by the banking network.
    - `processed`: The reverse wire was successfully settled and funds have been received.
    - `rejected`: The reverse wire was rejected by the receiving bank (e.g. invalid account, insufficient funds).
    - `failed`: The reverse wire failed during processing due to a system or network error.

    """
    payment_direction: ReverseWireTransactionPaymentDirection
    r"""The direction of the payment. Reverse wires are always debits from the company's account."""
    created_at: str
    r"""The date the reverse wire record was created."""
    bank_name: NotRequired[Nullable[str]]
    r"""Name of the receiving bank. Null when the bank is not known."""
    payment_event_type: NotRequired[Nullable[ReverseWireTransactionPaymentEventType]]
    r"""The type of payment event this reverse wire is associated with. Null when the wire is not linked to a payroll or contractor payment."""
    payment_event_uuid: NotRequired[Nullable[str]]
    r"""Unique identifier of the associated payroll or contractor payment. Null when the wire is not linked to a payment event."""
    payment_event_check_date: NotRequired[Nullable[str]]
    r"""The check date of the associated payment event. Null when the wire is not linked to a payment event."""


class ReverseWireTransaction(BaseModel):
    r"""Representation of a reverse wire (drawdown) transaction. Reverse wires are debit transactions initiated by Gusto to pull funds from a partner's bank account to cover payroll or contractor payment obligations."""

    company_uuid: str
    r"""Unique identifier of the company the reverse wire transaction belongs to"""

    amount: str
    r"""The amount of money moved by the reverse wire, as a decimal string. Always non-negative."""

    status: ReverseWireTransactionStatus
    r"""Current status of the reverse wire transaction.
    - `pending_processing`: The reverse wire has been initiated and is awaiting processing by the banking network.
    - `processed`: The reverse wire was successfully settled and funds have been received.
    - `rejected`: The reverse wire was rejected by the receiving bank (e.g. invalid account, insufficient funds).
    - `failed`: The reverse wire failed during processing due to a system or network error.

    """

    payment_direction: ReverseWireTransactionPaymentDirection
    r"""The direction of the payment. Reverse wires are always debits from the company's account."""

    created_at: str
    r"""The date the reverse wire record was created."""

    bank_name: OptionalNullable[str] = UNSET
    r"""Name of the receiving bank. Null when the bank is not known."""

    payment_event_type: OptionalNullable[ReverseWireTransactionPaymentEventType] = UNSET
    r"""The type of payment event this reverse wire is associated with. Null when the wire is not linked to a payroll or contractor payment."""

    payment_event_uuid: OptionalNullable[str] = UNSET
    r"""Unique identifier of the associated payroll or contractor payment. Null when the wire is not linked to a payment event."""

    payment_event_check_date: OptionalNullable[str] = UNSET
    r"""The check date of the associated payment event. Null when the wire is not linked to a payment event."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "bank_name",
                "payment_event_type",
                "payment_event_uuid",
                "payment_event_check_date",
            ]
        )
        nullable_fields = set(
            [
                "bank_name",
                "payment_event_type",
                "payment_event_uuid",
                "payment_event_check_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
