"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bulk_report_custom_report_item import (
    BulkReportCustomReportItem,
    BulkReportCustomReportItemTypedDict,
)
from .bulk_report_general_ledger_item import (
    BulkReportGeneralLedgerItem,
    BulkReportGeneralLedgerItemTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


BulkReportItemTypedDict = TypeAliasType(
    "BulkReportItemTypedDict",
    Union[BulkReportGeneralLedgerItemTypedDict, BulkReportCustomReportItemTypedDict],
)
r"""A single report inside a bulk batch. Required fields depend on `report_type`: `custom_report` requires `columns` and `file_type`; `general_ledger` requires `payroll_uuid` and `aggregation`."""


BulkReportItem = Annotated[
    Union[BulkReportCustomReportItem, BulkReportGeneralLedgerItem],
    Field(discriminator="report_type"),
]
r"""A single report inside a bulk batch. Required fields depend on `report_type`: `custom_report` requires `columns` and `file_type`; `general_ledger` requires `payroll_uuid` and `aggregation`."""
