"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contractor_payment_for_group import (
    ContractorPaymentForGroup,
    ContractorPaymentForGroupTypedDict,
)
from .payroll_credit_blocker_type import (
    PayrollCreditBlockerType,
    PayrollCreditBlockerTypeTypedDict,
)
from .payroll_submission_blocker_type import (
    PayrollSubmissionBlockerType,
    PayrollSubmissionBlockerTypeTypedDict,
)
from enum import Enum
from gusto_embedded_v_2026_06_15 import models, utils
from gusto_embedded_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ContractorPaymentGroupStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the contractor payment group.  Will be `Funded` if all payments that should be funded (i.e. have `Direct Deposit` for payment method) are funded.  A group can have status `Funded` while having associated payments that have status `Unfunded`, i.e. payment with `Check` payment method."""

    UNFUNDED = "Unfunded"
    FUNDED = "Funded"


class ContractorPaymentGroupTotalsTypedDict(TypedDict):
    amount: NotRequired[str]
    r"""The total amount for the group of contractor payments."""
    debit_amount: NotRequired[str]
    r"""The total debit amount for the group of contractor payments. Sum of wage & reimbursement amount."""
    wage_amount: NotRequired[str]
    r"""The total wage amount for the group of contractor payments."""
    reimbursement_amount: NotRequired[str]
    r"""The total reimbursement amount for the group of contractor payments."""
    check_amount: NotRequired[str]
    r"""The total check amount for the group of contractor payments."""


class ContractorPaymentGroupTotals(BaseModel):
    amount: Optional[str] = None
    r"""The total amount for the group of contractor payments."""

    debit_amount: Optional[str] = None
    r"""The total debit amount for the group of contractor payments. Sum of wage & reimbursement amount."""

    wage_amount: Optional[str] = None
    r"""The total wage amount for the group of contractor payments."""

    reimbursement_amount: Optional[str] = None
    r"""The total reimbursement amount for the group of contractor payments."""

    check_amount: Optional[str] = None
    r"""The total check amount for the group of contractor payments."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "debit_amount",
                "wage_amount",
                "reimbursement_amount",
                "check_amount",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ContractorPaymentGroupTypedDict(TypedDict):
    r"""The full contractor payment group, including associated contractor payments."""

    uuid: NotRequired[str]
    r"""The unique identifier of the contractor payment group."""
    company_uuid: NotRequired[str]
    r"""The UUID of the company."""
    check_date: NotRequired[str]
    r"""The check date of the contractor payment group."""
    debit_date: NotRequired[str]
    r"""The debit date of the contractor payment group."""
    status: NotRequired[ContractorPaymentGroupStatus]
    r"""The status of the contractor payment group.  Will be `Funded` if all payments that should be funded (i.e. have `Direct Deposit` for payment method) are funded.  A group can have status `Funded` while having associated payments that have status `Unfunded`, i.e. payment with `Check` payment method."""
    creation_token: NotRequired[Nullable[str]]
    r"""Token used to make contractor payment group creation idempotent.  Will error if attempting to create a group with a duplicate token."""
    partner_owned_disbursement: NotRequired[Nullable[bool]]
    r"""Whether the disbursement is partner owned."""
    submission_blockers: NotRequired[List[PayrollSubmissionBlockerTypeTypedDict]]
    r"""List of submission blockers for the contractor payment group."""
    credit_blockers: NotRequired[List[PayrollCreditBlockerTypeTypedDict]]
    r"""List of credit blockers for the contractor payment group."""
    totals: NotRequired[ContractorPaymentGroupTotalsTypedDict]
    contractor_payments: NotRequired[List[ContractorPaymentForGroupTypedDict]]


class ContractorPaymentGroup(BaseModel):
    r"""The full contractor payment group, including associated contractor payments."""

    uuid: Optional[str] = None
    r"""The unique identifier of the contractor payment group."""

    company_uuid: Optional[str] = None
    r"""The UUID of the company."""

    check_date: Optional[str] = None
    r"""The check date of the contractor payment group."""

    debit_date: Optional[str] = None
    r"""The debit date of the contractor payment group."""

    status: Optional[ContractorPaymentGroupStatus] = None
    r"""The status of the contractor payment group.  Will be `Funded` if all payments that should be funded (i.e. have `Direct Deposit` for payment method) are funded.  A group can have status `Funded` while having associated payments that have status `Unfunded`, i.e. payment with `Check` payment method."""

    creation_token: OptionalNullable[str] = UNSET
    r"""Token used to make contractor payment group creation idempotent.  Will error if attempting to create a group with a duplicate token."""

    partner_owned_disbursement: OptionalNullable[bool] = UNSET
    r"""Whether the disbursement is partner owned."""

    submission_blockers: Optional[List[PayrollSubmissionBlockerType]] = None
    r"""List of submission blockers for the contractor payment group."""

    credit_blockers: Optional[List[PayrollCreditBlockerType]] = None
    r"""List of credit blockers for the contractor payment group."""

    totals: Optional[ContractorPaymentGroupTotals] = None

    contractor_payments: Optional[List[ContractorPaymentForGroup]] = None

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentGroupStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "uuid",
                "company_uuid",
                "check_date",
                "debit_date",
                "status",
                "creation_token",
                "partner_owned_disbursement",
                "submission_blockers",
                "credit_blockers",
                "totals",
                "contractor_payments",
            ]
        )
        nullable_fields = set(["creation_token", "partner_owned_disbursement"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
