"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from enum import Enum
from gusto_embedded_v_2026_06_15 import models, utils
from gusto_embedded_v_2026_06_15.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ContractorPaymentListingPaymentMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The payment method."""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"
    HISTORICAL_PAYMENT = "Historical Payment"
    CORRECTION_PAYMENT = "Correction Payment"


class ContractorPaymentListingStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Contractor payment status"""

    FUNDED = "Funded"
    UNFUNDED = "Unfunded"


class ContractorPaymentListingWageType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The wage type for the payment."""

    HOURLY = "Hourly"
    FIXED = "Fixed"


class ContractorPaymentListingTypedDict(TypedDict):
    r"""The representation of a contractor payment as it appears in a contractor's payment history."""

    uuid: str
    r"""The unique identifier of the contractor payment in Gusto."""
    check_date: NotRequired[date]
    r"""The check date for the payment."""
    bonus: NotRequired[str]
    r"""The bonus amount in the payment."""
    hours: NotRequired[str]
    r"""The number of hours worked for the payment."""
    hourly_rate: NotRequired[str]
    r"""The rate per hour worked for the payment."""
    payment_method: NotRequired[ContractorPaymentListingPaymentMethod]
    r"""The payment method."""
    reimbursement: NotRequired[str]
    r"""The reimbursement amount in the payment."""
    status: NotRequired[ContractorPaymentListingStatus]
    r"""Contractor payment status"""
    wage: NotRequired[str]
    r"""The fixed wage of the payment, regardless of hours worked."""
    wage_type: NotRequired[ContractorPaymentListingWageType]
    r"""The wage type for the payment."""
    wage_total: NotRequired[str]
    r"""(hours * hourly_rate) + wage + bonus"""


class ContractorPaymentListing(BaseModel):
    r"""The representation of a contractor payment as it appears in a contractor's payment history."""

    uuid: str
    r"""The unique identifier of the contractor payment in Gusto."""

    check_date: Optional[date] = None
    r"""The check date for the payment."""

    bonus: Optional[str] = None
    r"""The bonus amount in the payment."""

    hours: Optional[str] = None
    r"""The number of hours worked for the payment."""

    hourly_rate: Optional[str] = None
    r"""The rate per hour worked for the payment."""

    payment_method: Optional[ContractorPaymentListingPaymentMethod] = None
    r"""The payment method."""

    reimbursement: Optional[str] = None
    r"""The reimbursement amount in the payment."""

    status: Optional[ContractorPaymentListingStatus] = None
    r"""Contractor payment status"""

    wage: Optional[str] = None
    r"""The fixed wage of the payment, regardless of hours worked."""

    wage_type: Optional[ContractorPaymentListingWageType] = None
    r"""The wage type for the payment."""

    wage_total: Optional[str] = None
    r"""(hours * hourly_rate) + wage + bonus"""

    @field_serializer("payment_method")
    def serialize_payment_method(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentListingPaymentMethod(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentListingStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("wage_type")
    def serialize_wage_type(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentListingWageType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "check_date",
                "bonus",
                "hours",
                "hourly_rate",
                "payment_method",
                "reimbursement",
                "status",
                "wage",
                "wage_type",
                "wage_total",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
