"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .employee_state_tax_answer import (
    EmployeeStateTaxAnswer,
    EmployeeStateTaxAnswerTypedDict,
)
from .employee_state_tax_input_question_format import (
    EmployeeStateTaxInputQuestionFormat,
    EmployeeStateTaxInputQuestionFormatTypedDict,
)
from gusto_embedded_v_2026_06_15.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import TypedDict


class EmployeeStateTaxQuestionTypedDict(TypedDict):
    label: str
    r"""A short title for the question"""
    description: Nullable[str]
    r"""An explaination of the question - this may contain inline html formatted links."""
    key: str
    r"""A unique identifier of the question (for the given state) - used for updating the answer."""
    is_question_for_admin_only: bool
    input_question_format: EmployeeStateTaxInputQuestionFormatTypedDict
    answers: List[EmployeeStateTaxAnswerTypedDict]


class EmployeeStateTaxQuestion(BaseModel):
    label: str
    r"""A short title for the question"""

    description: Nullable[str]
    r"""An explaination of the question - this may contain inline html formatted links."""

    key: str
    r"""A unique identifier of the question (for the given state) - used for updating the answer."""

    is_question_for_admin_only: bool

    input_question_format: EmployeeStateTaxInputQuestionFormat

    answers: List[EmployeeStateTaxAnswer]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
