"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from gusto_embedded_v_2026_06_15.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EmployeeFederalTaxPre2020TypedDict(TypedDict):
    r"""Federal tax information for employees using the pre-2020 W4 form."""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""
    additional_withholding: str
    r"""An additional withholding dollar amount."""
    employee_uuid: NotRequired[str]
    r"""The UUID of the employee."""
    employee_id: NotRequired[int]
    r"""The internal ID of the employee."""
    company_id: NotRequired[int]
    r"""The internal ID of the company."""
    w4_data_type: Literal["pre_2020_w4"]
    r"""The version of w4 form."""
    filing_status: NotRequired[Nullable[str]]
    r"""It determines which tax return form an individual will use and is an important factor in computing taxable income. One of:
    - Single
    - Married
    - Head of Household
    - Exempt from withholding
    - Married, but withhold as Single
    """
    federal_withholding_allowance: NotRequired[Nullable[float]]
    r"""An exemption from paying a certain amount of income tax. May be null when filing_status is \"Exempt from withholding\"."""


class EmployeeFederalTaxPre2020(BaseModel):
    r"""Federal tax information for employees using the pre-2020 W4 form."""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field."""

    additional_withholding: str
    r"""An additional withholding dollar amount."""

    employee_uuid: Optional[str] = None
    r"""The UUID of the employee."""

    employee_id: Optional[int] = None
    r"""The internal ID of the employee."""

    company_id: Optional[int] = None
    r"""The internal ID of the company."""

    w4_data_type: Annotated[
        Annotated[
            Literal["pre_2020_w4"], AfterValidator(validate_const("pre_2020_w4"))
        ],
        pydantic.Field(alias="w4_data_type"),
    ] = "pre_2020_w4"
    r"""The version of w4 form."""

    filing_status: OptionalNullable[str] = UNSET
    r"""It determines which tax return form an individual will use and is an important factor in computing taxable income. One of:
    - Single
    - Married
    - Head of Household
    - Exempt from withholding
    - Married, but withhold as Single
    """

    federal_withholding_allowance: OptionalNullable[float] = UNSET
    r"""An exemption from paying a certain amount of income tax. May be null when filing_status is \"Exempt from withholding\"."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "employee_uuid",
                "employee_id",
                "company_id",
                "filing_status",
                "federal_withholding_allowance",
            ]
        )
        nullable_fields = set(["filing_status", "federal_withholding_allowance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    EmployeeFederalTaxPre2020.model_rebuild()
except NameError:
    pass
