"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2026_06_15.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class NewYearsDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class NewYearsDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MlkDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class MlkDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PresidentsDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class PresidentsDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MemorialDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class MemorialDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class JuneteenthTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class Juneteenth(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class IndependenceDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class IndependenceDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LaborDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class LaborDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ColumbusDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class ColumbusDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VeteransDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class VeteransDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ThanksgivingTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class Thanksgiving(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ChristmasDayTypedDict(TypedDict):
    selected: NotRequired[bool]
    name: NotRequired[str]
    date_: NotRequired[str]


class ChristmasDay(BaseModel):
    selected: Optional[bool] = None

    name: Optional[str] = None

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["selected", "name", "date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FederalHolidaysTypedDict(TypedDict):
    r"""List of the eleven supported federal holidays and their details"""

    new_years_day: NotRequired[NewYearsDayTypedDict]
    mlk_day: NotRequired[MlkDayTypedDict]
    presidents_day: NotRequired[PresidentsDayTypedDict]
    memorial_day: NotRequired[MemorialDayTypedDict]
    juneteenth: NotRequired[JuneteenthTypedDict]
    independence_day: NotRequired[IndependenceDayTypedDict]
    labor_day: NotRequired[LaborDayTypedDict]
    columbus_day: NotRequired[ColumbusDayTypedDict]
    veterans_day: NotRequired[VeteransDayTypedDict]
    thanksgiving: NotRequired[ThanksgivingTypedDict]
    christmas_day: NotRequired[ChristmasDayTypedDict]


class FederalHolidays(BaseModel):
    r"""List of the eleven supported federal holidays and their details"""

    new_years_day: Optional[NewYearsDay] = None

    mlk_day: Optional[MlkDay] = None

    presidents_day: Optional[PresidentsDay] = None

    memorial_day: Optional[MemorialDay] = None

    juneteenth: Optional[Juneteenth] = None

    independence_day: Optional[IndependenceDay] = None

    labor_day: Optional[LaborDay] = None

    columbus_day: Optional[ColumbusDay] = None

    veterans_day: Optional[VeteransDay] = None

    thanksgiving: Optional[Thanksgiving] = None

    christmas_day: Optional[ChristmasDay] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "new_years_day",
                "mlk_day",
                "presidents_day",
                "memorial_day",
                "juneteenth",
                "independence_day",
                "labor_day",
                "columbus_day",
                "veterans_day",
                "thanksgiving",
                "christmas_day",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HolidayPayPolicyEmployeesTypedDict(TypedDict):
    uuid: NotRequired[str]


class HolidayPayPolicyEmployees(BaseModel):
    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HolidayPayPolicyTypedDict(TypedDict):
    r"""Representation of a Holiday Pay Policy"""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field."""
    company_uuid: str
    r"""A unique identifier for the company owning the holiday pay policy"""
    federal_holidays: FederalHolidaysTypedDict
    r"""List of the eleven supported federal holidays and their details"""
    employees: List[HolidayPayPolicyEmployeesTypedDict]
    r"""List of employee uuids under a holiday pay policy"""


class HolidayPayPolicy(BaseModel):
    r"""Representation of a Holiday Pay Policy"""

    version: str
    r"""The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field."""

    company_uuid: str
    r"""A unique identifier for the company owning the holiday pay policy"""

    federal_holidays: FederalHolidays
    r"""List of the eleven supported federal holidays and their details"""

    employees: List[HolidayPayPolicyEmployees]
    r"""List of employee uuids under a holiday pay policy"""


try:
    NewYearsDay.model_rebuild()
except NameError:
    pass
try:
    MlkDay.model_rebuild()
except NameError:
    pass
try:
    PresidentsDay.model_rebuild()
except NameError:
    pass
try:
    MemorialDay.model_rebuild()
except NameError:
    pass
try:
    Juneteenth.model_rebuild()
except NameError:
    pass
try:
    IndependenceDay.model_rebuild()
except NameError:
    pass
try:
    LaborDay.model_rebuild()
except NameError:
    pass
try:
    ColumbusDay.model_rebuild()
except NameError:
    pass
try:
    VeteransDay.model_rebuild()
except NameError:
    pass
try:
    Thanksgiving.model_rebuild()
except NameError:
    pass
try:
    ChristmasDay.model_rebuild()
except NameError:
    pass
