"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2026_06_15.types import BaseModel
from typing_extensions import TypedDict


class PartnerManagedCompanyDisassociateResponseTypedDict(TypedDict):
    r"""The company that was disassociated from the partner's embedded payroll product."""

    company_uuid: str
    r"""The UUID of the disassociated company."""
    company_name: str
    r"""The name of the disassociated company."""


class PartnerManagedCompanyDisassociateResponse(BaseModel):
    r"""The company that was disassociated from the partner's embedded payroll product."""

    company_uuid: str
    r"""The UUID of the disassociated company."""

    company_name: str
    r"""The name of the disassociated company."""
