"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_embedded_v_2026_06_15.types import BaseModel
from gusto_embedded_v_2026_06_15.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadataTypedDict(TypedDict):
    pass


class PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadata(BaseModel):
    pass


class PayrollCreditBlockerUnblockOptionWaitForReverseWireTypedDict(TypedDict):
    r"""Unblock option to resolve a credit blocker by waiting for reverse wire"""

    check_date: str
    r"""The payment check date associated with the unblock option"""
    metadata: PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadataTypedDict
    unblock_type: Literal["wait_for_reverse_wire"]
    r"""The type of unblock option for the credit blocker"""


class PayrollCreditBlockerUnblockOptionWaitForReverseWire(BaseModel):
    r"""Unblock option to resolve a credit blocker by waiting for reverse wire"""

    check_date: str
    r"""The payment check date associated with the unblock option"""

    metadata: PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadata

    unblock_type: Annotated[
        Annotated[
            Literal["wait_for_reverse_wire"],
            AfterValidator(validate_const("wait_for_reverse_wire")),
        ],
        pydantic.Field(alias="unblock_type"),
    ] = "wait_for_reverse_wire"
    r"""The type of unblock option for the credit blocker"""


try:
    PayrollCreditBlockerUnblockOptionWaitForReverseWire.model_rebuild()
except NameError:
    pass
