"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entity_error_object import EntityErrorObject, EntityErrorObjectTypedDict
from enum import Enum
from gusto_embedded_v_2026_06_15 import models, utils
from gusto_embedded_v_2026_06_15.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PayrollProcessingRequestStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the payroll processing request"""

    CALCULATING = "calculating"
    CALCULATE_SUCCESS = "calculate_success"
    SUBMITTING = "submitting"
    SUBMIT_SUCCESS = "submit_success"
    PROCESSING_FAILED = "processing_failed"


class PayrollProcessingRequestTypedDict(TypedDict):
    status: NotRequired[PayrollProcessingRequestStatus]
    r"""The status of the payroll processing request"""
    errors: NotRequired[List[EntityErrorObjectTypedDict]]
    r"""Errors that occurred during async payroll processing"""


class PayrollProcessingRequest(BaseModel):
    status: Optional[PayrollProcessingRequestStatus] = None
    r"""The status of the payroll processing request"""

    errors: Optional[List[EntityErrorObject]] = None
    r"""Errors that occurred during async payroll processing"""

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.PayrollProcessingRequestStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "errors"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
