"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_embedded_v_2026_06_15.types import BaseModel
from typing_extensions import TypedDict


class OwnerType(str, Enum):
    r"""The owner type of the bank account"""

    COMPANY = "Company"


class PlaidProcessorTokenRequestTypedDict(TypedDict):
    r"""Request body for creating a verified company bank account from a Plaid processor token."""

    owner_type: OwnerType
    r"""The owner type of the bank account"""
    owner_id: str
    r"""The owner UUID of the bank account"""
    processor_token: str
    r"""The Plaid processor token"""


class PlaidProcessorTokenRequest(BaseModel):
    r"""Request body for creating a verified company bank account from a Plaid processor token."""

    owner_type: OwnerType
    r"""The owner type of the bank account"""

    owner_id: str
    r"""The owner UUID of the bank account"""

    processor_token: str
    r"""The Plaid processor token"""
