"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from enum import Enum
from gusto_embedded_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from gusto_embedded_v_2026_06_15.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostV1EmployeesHeaderXGustoAPIVersion(str, Enum):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_SIX_MINUS_06_MINUS_15 = "2026-06-15"


class PostV1EmployeesRequestBodyTypedDict(TypedDict):
    first_name: str
    last_name: str
    middle_initial: NotRequired[str]
    email: NotRequired[Nullable[str]]
    r"""The employee's personal email address. Required if self_onboarding is true."""
    work_email: NotRequired[str]
    r"""The employee's work email address."""
    date_of_birth: NotRequired[date]
    ssn: NotRequired[str]
    preferred_first_name: NotRequired[str]
    self_onboarding: NotRequired[bool]
    r"""If true, employee is expected to self-onboard. If false, payroll admin is expected to enter in the employee's onboarding information"""


class PostV1EmployeesRequestBody(BaseModel):
    first_name: str

    last_name: str

    middle_initial: Optional[str] = None

    email: OptionalNullable[str] = UNSET
    r"""The employee's personal email address. Required if self_onboarding is true."""

    work_email: Optional[str] = None
    r"""The employee's work email address."""

    date_of_birth: Optional[date] = None

    ssn: Optional[str] = None

    preferred_first_name: Optional[str] = None

    self_onboarding: Optional[bool] = None
    r"""If true, employee is expected to self-onboard. If false, payroll admin is expected to enter in the employee's onboarding information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "middle_initial",
                "email",
                "work_email",
                "date_of_birth",
                "ssn",
                "preferred_first_name",
                "self_onboarding",
            ]
        )
        nullable_fields = set(["email"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PostV1EmployeesRequestTypedDict(TypedDict):
    company_id: str
    r"""Company ID"""
    x_gusto_api_version: NotRequired[PostV1EmployeesHeaderXGustoAPIVersion]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""
    body: NotRequired[PostV1EmployeesRequestBodyTypedDict]


class PostV1EmployeesRequest(BaseModel):
    company_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Company ID"""

    x_gusto_api_version: Annotated[
        Optional[PostV1EmployeesHeaderXGustoAPIVersion],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = PostV1EmployeesHeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_SIX_MINUS_06_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    body: Annotated[
        Optional[PostV1EmployeesRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version", "body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
