"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entity_error_object import EntityErrorObject
from dataclasses import dataclass, field
from gusto_embedded_v_2026_06_15.models import GustoError
from gusto_embedded_v_2026_06_15.types import BaseModel
import httpx
from typing import List, Optional


class UnprocessableEntityError1Data(BaseModel):
    errors: List[EntityErrorObject]


@dataclass(unsafe_hash=True)
class UnprocessableEntityError1(GustoError):
    r"""Unprocessable Entity

    This may happen when the body of your request contains errors such as `invalid_attribute_value`, or the request fails due to an `invalid_operation`. See the [Errors Categories](https://docs.gusto.com/embedded-payroll/docs/error-categories) guide for more details.

    """

    data: UnprocessableEntityError1Data = field(hash=False)

    def __init__(
        self,
        data: UnprocessableEntityError1Data,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
