"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TimeSheetSortBy(str, Enum):
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    SHIFT_STARTED_AT = "shift_started_at"
    SHIFT_ENDED_AT = "shift_ended_at"
