"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .company_custom_field import CompanyCustomField, CompanyCustomFieldTypedDict
from gusto_app_integration_v_2026_06_15.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CompanyCustomFieldListTypedDict(TypedDict):
    custom_fields: NotRequired[List[CompanyCustomFieldTypedDict]]


class CompanyCustomFieldList(BaseModel):
    custom_fields: Optional[List[CompanyCustomField]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["custom_fields"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
