"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_app_integration_v_2026_06_15 import models, utils
from gusto_app_integration_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ContractorPaymentPaymentMethod(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The payment method."""

    DIRECT_DEPOSIT = "Direct Deposit"
    CHECK = "Check"
    HISTORICAL_PAYMENT = "Historical Payment"
    CORRECTION_PAYMENT = "Correction Payment"


class ContractorPaymentStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Contractor payment status"""

    FUNDED = "Funded"
    UNFUNDED = "Unfunded"


class WageType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The wage type for the payment."""

    HOURLY = "Hourly"
    FIXED = "Fixed"


class ContractorPaymentTypedDict(TypedDict):
    r"""The representation of a single contractor payment."""

    uuid: str
    r"""The unique identifier of the contractor payment in Gusto."""
    contractor_uuid: NotRequired[str]
    r"""The UUID of the contractor."""
    bonus: NotRequired[str]
    r"""The bonus amount in the payment."""
    date_: NotRequired[str]
    r"""The payment date."""
    hours: NotRequired[str]
    r"""The number of hours worked for the payment."""
    payment_method: NotRequired[ContractorPaymentPaymentMethod]
    r"""The payment method."""
    reimbursement: NotRequired[str]
    r"""The reimbursement amount in the payment."""
    status: NotRequired[ContractorPaymentStatus]
    r"""Contractor payment status"""
    hourly_rate: NotRequired[str]
    r"""The rate per hour worked for the payment."""
    may_cancel: NotRequired[bool]
    r"""Determine if the contractor payment can be cancelled."""
    wage: NotRequired[str]
    r"""The fixed wage of the payment, regardless of hours worked."""
    wage_type: NotRequired[WageType]
    r"""The wage type for the payment."""
    wage_total: NotRequired[str]
    r"""(hours * hourly_rate) + wage + bonus"""
    invoice_number: NotRequired[Nullable[str]]
    r"""An optional invoice number associated with this contractor payment. This will be visible to the contractor on their paystub. Maximum 25 characters."""
    memo: NotRequired[Nullable[str]]
    r"""An optional note or memo for this contractor payment. This will be visible to the contractor on their paystub."""


class ContractorPayment(BaseModel):
    r"""The representation of a single contractor payment."""

    uuid: str
    r"""The unique identifier of the contractor payment in Gusto."""

    contractor_uuid: Optional[str] = None
    r"""The UUID of the contractor."""

    bonus: Optional[str] = None
    r"""The bonus amount in the payment."""

    date_: Annotated[Optional[str], pydantic.Field(alias="date")] = None
    r"""The payment date."""

    hours: Optional[str] = None
    r"""The number of hours worked for the payment."""

    payment_method: Optional[ContractorPaymentPaymentMethod] = None
    r"""The payment method."""

    reimbursement: Optional[str] = None
    r"""The reimbursement amount in the payment."""

    status: Optional[ContractorPaymentStatus] = None
    r"""Contractor payment status"""

    hourly_rate: Optional[str] = None
    r"""The rate per hour worked for the payment."""

    may_cancel: Optional[bool] = None
    r"""Determine if the contractor payment can be cancelled."""

    wage: Optional[str] = None
    r"""The fixed wage of the payment, regardless of hours worked."""

    wage_type: Optional[WageType] = None
    r"""The wage type for the payment."""

    wage_total: Optional[str] = None
    r"""(hours * hourly_rate) + wage + bonus"""

    invoice_number: OptionalNullable[str] = UNSET
    r"""An optional invoice number associated with this contractor payment. This will be visible to the contractor on their paystub. Maximum 25 characters."""

    memo: OptionalNullable[str] = UNSET
    r"""An optional note or memo for this contractor payment. This will be visible to the contractor on their paystub."""

    @field_serializer("payment_method")
    def serialize_payment_method(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentPaymentMethod(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.ContractorPaymentStatus(value)
            except ValueError:
                return value
        return value

    @field_serializer("wage_type")
    def serialize_wage_type(self, value):
        if isinstance(value, str):
            try:
                return models.WageType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "contractor_uuid",
                "bonus",
                "date",
                "hours",
                "payment_method",
                "reimbursement",
                "status",
                "hourly_rate",
                "may_cancel",
                "wage",
                "wage_type",
                "wage_total",
                "invoice_number",
                "memo",
            ]
        )
        nullable_fields = set(["invoice_number", "memo"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ContractorPayment.model_rebuild()
except NameError:
    pass
