"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_app_integration_v_2026_06_15.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class EmployeeSection603HighEarnerStatusTypedDict(TypedDict):
    r"""The representation of an employee's Section 603 high earner status for a specific year. Section 603 of the SECURE 2.0 Act requires employees aged 50 or older whose prior-year FICA wages exceed the IRS threshold to have their catch-up contributions to pre-tax retirement benefits designated as post-tax contributions."""

    id: str
    r"""The unique identifier of the Section 603 high earner status record"""
    effective_year: int
    r"""The year for which this high earner status applies"""
    is_high_earner: Nullable[bool]
    r"""Whether the employee is classified as a high earner for Section 603 purposes. Can be null if the status has not yet been determined."""


class EmployeeSection603HighEarnerStatus(BaseModel):
    r"""The representation of an employee's Section 603 high earner status for a specific year. Section 603 of the SECURE 2.0 Act requires employees aged 50 or older whose prior-year FICA wages exceed the IRS threshold to have their catch-up contributions to pre-tax retirement benefits designated as post-tax contributions."""

    id: str
    r"""The unique identifier of the Section 603 high earner status record"""

    effective_year: int
    r"""The year for which this high earner status applies"""

    is_high_earner: Nullable[bool]
    r"""Whether the employee is classified as a high earner for Section 603 purposes. Can be null if the status has not yet been determined."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
