"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from gusto_app_integration_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EmployeeHomeAddressHistoryEntryTypedDict(TypedDict):
    r"""A single entry in an employee's home-address history. Returned in the
    `all_home_addresses` array; includes the `effective_date` the address
    became active in addition to the shared `Employee-Home-Address` fields.

    """

    street_1: NotRequired[Nullable[str]]
    street_2: NotRequired[Nullable[str]]
    city: NotRequired[Nullable[str]]
    state: NotRequired[Nullable[str]]
    zip_code: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]
    active: NotRequired[bool]
    r"""The status of the location. Inactive locations have been deleted, but may still have historical data associated with them."""
    uuid: NotRequired[str]
    r"""Unique identifier for this address."""
    effective_date: NotRequired[date]
    r"""The date the address became effective."""


class EmployeeHomeAddressHistoryEntry(BaseModel):
    r"""A single entry in an employee's home-address history. Returned in the
    `all_home_addresses` array; includes the `effective_date` the address
    became active in addition to the shared `Employee-Home-Address` fields.

    """

    street_1: OptionalNullable[str] = UNSET

    street_2: OptionalNullable[str] = UNSET

    city: OptionalNullable[str] = UNSET

    state: OptionalNullable[str] = UNSET

    zip_code: Annotated[OptionalNullable[str], pydantic.Field(alias="zip")] = UNSET

    country: OptionalNullable[str] = "USA"

    active: Optional[bool] = None
    r"""The status of the location. Inactive locations have been deleted, but may still have historical data associated with them."""

    uuid: Optional[str] = None
    r"""Unique identifier for this address."""

    effective_date: Optional[date] = None
    r"""The date the address became effective."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "street_1",
                "street_2",
                "city",
                "state",
                "zip_code",
                "country",
                "active",
                "uuid",
                "effective_date",
            ]
        )
        nullable_fields = set(
            ["street_1", "street_2", "city", "state", "zip_code", "country"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    EmployeeHomeAddressHistoryEntry.model_rebuild()
except NameError:
    pass
