"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_app_integration_v_2026_06_15.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PayScheduleAutoPayrollEnablementBlockerMetadataTypedDict(TypedDict):
    r"""Blocker-specific metadata (e.g. employee_uuids, states)."""


class PayScheduleAutoPayrollEnablementBlockerMetadata(BaseModel):
    r"""Blocker-specific metadata (e.g. employee_uuids, states)."""


class PayScheduleAutoPayrollEnablementBlockerTypedDict(TypedDict):
    r"""A single blocker preventing Autopayroll enablement."""

    key: NotRequired[str]
    r"""The blocker type (e.g. employees_not_on_direct_deposit, employees_not_salaried, missing_funding_method, missing_state_tax_requirements, one_day_ach_speed_not_supported, company_suspended, earned_fast_ach_not_met)."""
    metadata: NotRequired[PayScheduleAutoPayrollEnablementBlockerMetadataTypedDict]
    r"""Blocker-specific metadata (e.g. employee_uuids, states)."""


class PayScheduleAutoPayrollEnablementBlocker(BaseModel):
    r"""A single blocker preventing Autopayroll enablement."""

    key: Optional[str] = None
    r"""The blocker type (e.g. employees_not_on_direct_deposit, employees_not_salaried, missing_funding_method, missing_state_tax_requirements, one_day_ach_speed_not_supported, company_suspended, earned_fast_ach_not_met)."""

    metadata: Optional[PayScheduleAutoPayrollEnablementBlockerMetadata] = None
    r"""Blocker-specific metadata (e.g. employee_uuids, states)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
