"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_app_integration_v_2026_06_15 import models, utils
from gusto_app_integration_v_2026_06_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import field_serializer, model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class UnblockOptionsTypedDict(TypedDict):
    unblock_type: NotRequired[str]
    r"""The type of unblock option for the submission blocker."""
    check_date: NotRequired[str]
    r"""The payment check date associated with the unblock option."""
    metadata: NotRequired[Dict[str, Any]]
    r"""Additional data associated with the unblock option."""


class UnblockOptions(BaseModel):
    unblock_type: Optional[str] = None
    r"""The type of unblock option for the submission blocker."""

    check_date: Optional[str] = None
    r"""The payment check date associated with the unblock option."""

    metadata: Optional[Dict[str, Any]] = None
    r"""Additional data associated with the unblock option."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unblock_type", "check_date", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PayrollSubmissionBlockerTypeStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The status of the submission blocker."""

    UNRESOLVED = "unresolved"
    RESOLVED = "resolved"


class PayrollSubmissionBlockerTypeTypedDict(TypedDict):
    r"""A blocker that prevents payment submission."""

    blocker_type: NotRequired[str]
    r"""The type of blocker that's blocking the payment submission."""
    blocker_name: NotRequired[str]
    r"""The name of the submission blocker."""
    unblock_options: NotRequired[List[UnblockOptionsTypedDict]]
    r"""The available options to unblock a submission blocker."""
    selected_option: NotRequired[Nullable[str]]
    r"""The unblock option that's been selected to resolve the submission blocker."""
    status: NotRequired[PayrollSubmissionBlockerTypeStatus]
    r"""The status of the submission blocker."""


class PayrollSubmissionBlockerType(BaseModel):
    r"""A blocker that prevents payment submission."""

    blocker_type: Optional[str] = None
    r"""The type of blocker that's blocking the payment submission."""

    blocker_name: Optional[str] = None
    r"""The name of the submission blocker."""

    unblock_options: Optional[List[UnblockOptions]] = None
    r"""The available options to unblock a submission blocker."""

    selected_option: OptionalNullable[str] = UNSET
    r"""The unblock option that's been selected to resolve the submission blocker."""

    status: Optional[PayrollSubmissionBlockerTypeStatus] = None
    r"""The status of the submission blocker."""

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.PayrollSubmissionBlockerTypeStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "blocker_type",
                "blocker_name",
                "unblock_options",
                "selected_option",
                "status",
            ]
        )
        nullable_fields = set(["selected_option"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
