"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_app_integration.types import BaseModel, UNSET_SENTINEL
from gusto_app_integration.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    get_discriminator,
)
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class HeaderXGustoAPIVersion(str, Enum):
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15 = "2025-06-15"


class RequestBodyGrantType(str, Enum):
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""

    SYSTEM_ACCESS = "system_access"


class SystemAccessTokenRequestTypedDict(TypedDict):
    client_id: str
    r"""Your client ID"""
    client_secret: str
    r"""Your client secret"""
    grant_type: RequestBodyGrantType
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""


class SystemAccessTokenRequest(BaseModel):
    client_id: str
    r"""Your client ID"""

    client_secret: str
    r"""Your client secret"""

    grant_type: RequestBodyGrantType
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""


class GrantType(str, Enum):
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""

    REFRESH_TOKEN = "refresh_token"


class RefreshTokenRequestTypedDict(TypedDict):
    client_id: str
    r"""Your client ID"""
    client_secret: str
    r"""Your client secret"""
    grant_type: GrantType
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""
    refresh_token: str
    redirect_uri: NotRequired[str]
    r"""The redirect URI you set up via the Developer Portal"""


class RefreshTokenRequest(BaseModel):
    client_id: str
    r"""Your client ID"""

    client_secret: str
    r"""Your client secret"""

    grant_type: GrantType
    r"""Set system_access to create a system access token, refresh_token to refresh an existing token"""

    refresh_token: str

    redirect_uri: Optional[str] = None
    r"""The redirect URI you set up via the Developer Portal"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["redirect_uri"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


OauthAccessTokenRequestBodyTypedDict = TypeAliasType(
    "OauthAccessTokenRequestBodyTypedDict",
    Union[SystemAccessTokenRequestTypedDict, RefreshTokenRequestTypedDict],
)


OauthAccessTokenRequestBody = Annotated[
    Union[
        Annotated[RefreshTokenRequest, Tag("refresh_token")],
        Annotated[SystemAccessTokenRequest, Tag("system_access")],
    ],
    Discriminator(lambda m: get_discriminator(m, "grant_type", "grant_type")),
]


class OauthAccessTokenRequestTypedDict(TypedDict):
    request_body: OauthAccessTokenRequestBodyTypedDict
    x_gusto_api_version: NotRequired[HeaderXGustoAPIVersion]
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""


class OauthAccessTokenRequest(BaseModel):
    request_body: Annotated[
        OauthAccessTokenRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_gusto_api_version: Annotated[
        Optional[HeaderXGustoAPIVersion],
        pydantic.Field(alias="X-Gusto-API-Version"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = HeaderXGustoAPIVersion.TWO_THOUSAND_AND_TWENTY_FIVE_MINUS_06_MINUS_15
    r"""Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Gusto-API-Version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
