"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gusto_app_integration.types import BaseModel
from typing_extensions import TypedDict


class PayrollCreditBlockerUnblockOptionSubmitBankScreenshotUnblockType(str, Enum):
    r"""The type of unblock option for the credit blocker"""

    SUBMIT_BANK_SCREENSHOT = "submit_bank_screenshot"


class PayrollCreditBlockerUnblockOptionSubmitBankScreenshotMetadataTypedDict(TypedDict):
    information_request_uuid: str
    r"""UUID of the information request"""


class PayrollCreditBlockerUnblockOptionSubmitBankScreenshotMetadata(BaseModel):
    information_request_uuid: str
    r"""UUID of the information request"""


class PayrollCreditBlockerUnblockOptionSubmitBankScreenshotTypedDict(TypedDict):
    r"""Unblock option to resolve a credit blocker by submitting a bank screenshot"""

    unblock_type: PayrollCreditBlockerUnblockOptionSubmitBankScreenshotUnblockType
    r"""The type of unblock option for the credit blocker"""
    check_date: str
    r"""The payment check date associated with the unblock option"""
    metadata: PayrollCreditBlockerUnblockOptionSubmitBankScreenshotMetadataTypedDict


class PayrollCreditBlockerUnblockOptionSubmitBankScreenshot(BaseModel):
    r"""Unblock option to resolve a credit blocker by submitting a bank screenshot"""

    unblock_type: PayrollCreditBlockerUnblockOptionSubmitBankScreenshotUnblockType
    r"""The type of unblock option for the credit blocker"""

    check_date: str
    r"""The payment check date associated with the unblock option"""

    metadata: PayrollCreditBlockerUnblockOptionSubmitBankScreenshotMetadata
