"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_app_integration.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PayrollTaxesTypeTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The tax name"""
    employer: NotRequired[bool]
    r"""Whether this tax is an employer or employee tax"""
    amount: NotRequired[float]
    r"""The total tax for the payroll"""


class PayrollTaxesType(BaseModel):
    name: Optional[str] = None
    r"""The tax name"""

    employer: Optional[bool] = None
    r"""Whether this tax is an employer or employee tax"""

    amount: Optional[float] = None
    r"""The total tax for the payroll"""
