"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gusto_app_integration_v_2025_11_15.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from gusto_app_integration_v_2025_11_15.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadataTypedDict(TypedDict):
    reverse_wire_detail_id: NotRequired[Nullable[int]]
    r"""ID of the reverse wire detail"""
    bank_account_last_four_digits: NotRequired[Nullable[str]]
    r"""Last 4 digits of the bank account number for the reverse wire"""


class PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadata(BaseModel):
    reverse_wire_detail_id: OptionalNullable[int] = UNSET
    r"""ID of the reverse wire detail"""

    bank_account_last_four_digits: OptionalNullable[str] = UNSET
    r"""Last 4 digits of the bank account number for the reverse wire"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["reverse_wire_detail_id", "bank_account_last_four_digits"]
        )
        nullable_fields = set(
            ["reverse_wire_detail_id", "bank_account_last_four_digits"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PayrollCreditBlockerUnblockOptionWaitForReverseWireTypedDict(TypedDict):
    r"""Unblock option to resolve a credit blocker by waiting for reverse wire"""

    check_date: str
    r"""The payment check date associated with the unblock option"""
    metadata: PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadataTypedDict
    unblock_type: Literal["wait_for_reverse_wire"]
    r"""The type of unblock option for the credit blocker"""


class PayrollCreditBlockerUnblockOptionWaitForReverseWire(BaseModel):
    r"""Unblock option to resolve a credit blocker by waiting for reverse wire"""

    check_date: str
    r"""The payment check date associated with the unblock option"""

    metadata: PayrollCreditBlockerUnblockOptionWaitForReverseWireMetadata

    unblock_type: Annotated[
        Annotated[
            Literal["wait_for_reverse_wire"],
            AfterValidator(validate_const("wait_for_reverse_wire")),
        ],
        pydantic.Field(alias="unblock_type"),
    ] = "wait_for_reverse_wire"
    r"""The type of unblock option for the credit blocker"""


try:
    PayrollCreditBlockerUnblockOptionWaitForReverseWire.model_rebuild()
except NameError:
    pass
