name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  push:
    branches:
      - main
    paths:
      - gusto_embedded/.speakeasy/gen.lock
  workflow_dispatch: {}
jobs:
  publish-embedded:
    uses: Gusto/sdk-generation-action/.github/workflows/workflow-executor.yaml@main
    with:
      target: gusto
      runs-on: "{\"group\": \"gusto-ubuntu-default\"}"
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
  publish-app-int:
    uses: Gusto/sdk-generation-action/.github/workflows/workflow-executor.yaml@main
    with:
      target: gusto-app-int
      runs-on: "{\"group\": \"gusto-ubuntu-default\"}"
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
